[16.0][MIG] website_forum_subscription: Migration to version 16.0
OCA/website pull request #1010
Opened 2023-10-03 12:09 UTC by carolinafernandez-tecnativa

- Standard migration to v16

@Tecnativa

TT45242

@pedrobaeza @chienandalu

2023-10-03 13:08 UTC, chienandalu requested changes
Take care of bs4 -> bs5 classes changes (https://getbootstrap.com/docs/5.0/migration/#utilities)

A good custome is to use the tooling provided here to automate those checks: https://github.com/OCA/openupgradelib/pull/338

2023-10-03 13:08 UTC, chienandalu commented on website_forum_subscription/templates/website_forum_templates.xml
> +                        <small>Unsubscribe</small><i class="fa fa-fw ml-1" />
```suggestion
                        <small>Unsubscribe</small><i class="fa fa-fw ms-1" />
```

2023-10-03 13:08 UTC, chienandalu commented on website_forum_subscription/templates/website_forum_templates.xml
> +                        <small>Subscribe</small><i class="fa fa-fw ml-1" />
```suggestion
                        <small>Subscribe</small><i class="fa fa-fw ms-1" />
```

2023-10-03 13:17 UTC, carolinafernandez-tecnativa commented
> Take care of bs4 -> bs5 classes changes (https://getbootstrap.com/docs/5.0/migration/#utilities)
> 
> A good custome is to use the tooling provided here to automate those checks: [OCA/openupgradelib#338](https://github.com/OCA/openupgradelib/pull/338)

Hi thanks! How can i use that tool?

2023-10-03 13:37 UTC, chienandalu commented
> Hi thanks! How can i use that tool?

You'll have to build a version that includes that patch and then simply:
```python
from openupgradelib.openupgrade_160 import convert_string_bootstrap_4to5

xml = """<odoo><!-- Your xml --></odoo>"""
print(convert_string_bootstrap_4to5(xml))  # You can copy your output from the console directly
```

2023-10-03 15:21 UTC, carolinafernandez-tecnativa commented
WIP

2023-10-04 11:06 UTC, carolinafernandez-tecnativa commented
> > Hi thanks! How can i use that tool?
> 
> You'll have to build a version that includes that patch and then simply:
> 
> ```python
> from openupgradelib.openupgrade_160 import convert_string_bootstrap_4to5
> 
> xml = """<odoo><!-- Your xml --></odoo>"""
> print(convert_string_bootstrap_4to5(xml))  # You can copy your output from the console directly
> ```



> Take care of bs4 -> bs5 classes changes (https://getbootstrap.com/docs/5.0/migration/#utilities)
> 
> A good custome is to use the tooling provided here to automate those checks: [OCA/openupgradelib#338](https://github.com/OCA/openupgradelib/pull/338)

Goord morning,
Thanks for your help! I have checked and the only change was the one you detected, you can proceed to check it now 
FYI @pedrobaeza

2023-10-04 13:39 UTC, chienandalu approved these changes
:+1:

2023-10-04 18:56 UTC, pedrobaeza commented
/ocabot migration website_forum_subscription

2023-10-04 18:57 UTC, pedrobaeza approved these changes
Tested and working:

/ocabot merge nobump

2023-10-04 19:03 UTC, merged