[MIG] website_local_font: Migration to 16.0
OCA/website pull request #1028
Opened 2024-01-09 06:47 UTC by Reyes4711-S73

Standard migration to 16.0
Reopen from https://github.com/OCA/website/pull/999

2024-02-26 13:32 UTC, ByteMeAsap requested changes

2024-02-26 13:32 UTC, ByteMeAsap commented on website_local_font/__manifest__.py
> +            "website_local_font/static/src/xml/website.editor.xml",
Can you add this xml file to website.assets_wysiwyg asset instead of website_assets_backend? That way you don't need to define this in the snippets.options.js as xmldependency

2024-02-26 13:32 UTC, ByteMeAsap commented on website_local_font/static/src/js/snippets.options.js
[snippets.options.js.txt](https://github.com/OCA/website/files/14405362/snippets.options.js.txt)
Modify the code as shared in the attached file. I have removed xmlDependencies, inherited the start method in a way that it can be inherited by other modules in future, removed widgetObj in _saveLocalFont function and replaced by this and made use of "const" instead of "var"

2024-02-28 11:44 UTC, Reyes4711-S73 commented
@ByteMeAsap I put your changes but, I tested in a local environment and in a runboat and I have this error.
![image](https://github.com/OCA/website/assets/77978942/da80e482-7599-4424-be73-32903a189943)
When you modify the snippets.options.js, there are some errors in pre-commit. Please review it. I'm going to return to previous changes

2024-08-04 12:34 UTC, closed without merging