[MIG] website_google_tag_manager: Migration to 18.0
OCA/website pull request #1081
Opened 2024-12-24 07:30 UTC by SodexisTeam

2025-01-31 11:13 UTC, StefanRijnhart commented
/ocabot rebase

2025-01-31 11:13 UTC, StefanRijnhart commented
@SodexisTeam can you rebase to fix tests?

2025-01-31 13:59 UTC, amkarthik commented
@StefanRijnhart 
Done.

2025-01-31 15:27 UTC, StefanRijnhart commented
@amkarthik Did something not go as planned? I'm surprised to see that commits (and actual changes) that were merged to the 18.0 branch recently are now showing up here in this branch, as if the 18.0 branch was rebased onto this PR's branch rather than the other way around.
![image](https://github.com/user-attachments/assets/265d394f-b5f6-4e65-81f9-ddd889701b54)

2025-02-04 06:28 UTC, amkarthik commented
@StefanRijnhart 
I triggered "git pull oca 18.0 --rebase" to rebase the commits from oca repo and pushed it to PR branch
I am not sure why it's showing as you mentioned.
Please let me know If I miss something.
I have a backup of PR branch without any modifications in it.

2025-02-04 07:05 UTC, StefanRijnhart approved these changes
Thanks, all good now after the latest push!

2025-02-04 07:06 UTC, StefanRijnhart commented
/ocabot migration website_google_tag_manager

2025-02-05 18:31 UTC, desdelinux approved these changes

2025-02-05 18:31 UTC, desdelinux commented
Hi @StefanRijnhart @pedrobaeza this is ready :)

2025-02-11 17:42 UTC, JrAdhoc commented on website_google_tag_manager/views/website_templates.xml
> +        <xpath expr="//div[@id='wrapwrap']" position="after">
This part should be added right after the <body> opening tag, as mentioned in [this documentation](https://support.google.com/tagmanager/answer/14847097?hl=en&ref_topic=15191151&sjid=15285473597919634291-SA#)

2025-02-28 11:43 UTC, StefanRijnhart commented on website_google_tag_manager/views/website_templates.xml
> +        <xpath expr="//div[@id='wrapwrap']" position="after">
@SodexisTeam what do you think? Is this something that can be improved?

2025-04-29 09:57 UTC, TomAlbrechtQuatra commented on website_google_tag_manager/views/website_templates.xml
> +        <xpath expr="//div[@id='wrapwrap']" position="after">
It works if the code snippet is inside the <body>. However, the later it is added, the later it is loaded.
Which is not ideal, because you might miss some visitors. If this can be improved, that would be great

2025-05-08 08:15 UTC, StefanRijnhart commented on website_google_tag_manager/views/website_templates.xml
> +        <xpath expr="//div[@id='wrapwrap']" position="after">
Given that no response from @SodexisTeam has come in three months, @JrAdhoc I see you implemented this in your own migration PR of this module with the failing CI (https://github.com/OCA/website/pull/1064). Would you like to pick it up there?

2025-05-08 10:15 UTC, atchuthan commented on website_google_tag_manager/views/website_templates.xml
> +        <xpath expr="//div[@id='wrapwrap']" position="after">
We made the correction.  Please check @StefanRijnhart @TomAlbrechtQuatra @JrAdhoc

2025-05-08 10:36 UTC, StefanRijnhart commented on website_google_tag_manager/views/website_templates.xml
> +        <xpath expr="//div[@id='wrapwrap']" position="after">
Thanks! Is this alright with you @JrAdhoc?

2025-05-08 10:37 UTC, StefanRijnhart commented
/ocabot migration website_google_tag_manager

2025-06-19 11:53 UTC, pilarvargas-tecnativa requested changes
Please reduce administrative commits

2025-07-01 13:38 UTC, atchuthan commented
> Please reduce administrative commits

Reduced commits as per https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate
Please review @pilarvargas-tecnativa

2025-07-23 07:30 UTC, DavidJForgeFlow approved these changes

2025-07-23 09:05 UTC, StefanRijnhart commented
Looks like all comments have been addressed!

/ocabot merge nobump

2025-07-23 09:11 UTC, merged