[IMP][website_seo_redirection] New features and bug fixes. (#246)
OCA/website pull request #254
Opened 2016-09-08 09:08 UTC by Yajo

Forward #246 to v9.

- Fix a bug that was redirecting to disabled languages if the user's browser was in an installed language that was disabled for the website.
- Allow to have several origins for a destination.
- Disallow recursive redirections.
- Add both original and redirected URLs to web editor link search.
- Cannot have a redirection to yourself, now as a SQL constraint.
- Rename "Redirected URL" to "Destination URL" (seems more self-explicative).
- Add support for redirections that don't replace the controller (AKA shortcuts).
- Allow to choose a page URL from the "Promote" menu.
- Fix some styling issues, including `"use strict"` outside the function block.
- Tests, tests, tests (man, those JSONRPC ones were hard).

2016-09-08 10:38 UTC, pedrobaeza commented
With the renaming capability of v9, it's still needed all the part of changing the URL?

2016-09-08 13:25 UTC, Yajo commented
I did not try, but probably, if you don't want to lose SEO score, yes.

2016-09-10 06:13 UTC, rafaelbn commented
Hi @Yajo , travis fails

2016-10-04 09:30 UTC, rafaelbn requested changes
Hi @Yajo , please solve branch conflicts and review travis. Thanks

2016-10-11 09:13 UTC, pedrobaeza commented
Can you rebase this and check my question, @Yajo?

2016-10-11 11:24 UTC, Yajo commented
Let's see what does the bot say.

2016-10-11 11:29 UTC, Yajo commented
BTW, about https://github.com/OCA/website/pull/254#issuecomment-245559390, if you use the renaming function, you get a 404 error in old URL, while with this you get a 301 redirection. I think it still has a meaning for SEO freaks.

2016-10-11 11:39 UTC, Yajo commented
Well, bots are :white_check_mark:, but it's fake. They are affected by https://github.com/odoo/odoo/pull/13743. It seems Travis has no `sass` executable. Who should I ping for the fix?

2016-10-11 11:42 UTC, pedrobaeza commented
Not really fake, but not "covered" due to an Odoo bug. You can ping to the JS lead developer you met at Odoo experience to see, but we can't block this due to that question, or should we?

2016-10-11 11:46 UTC, Yajo commented
It is fake because they should go :x:, that developer is already pinged in the issue.

However, [tests for this addon are passing](https://travis-ci.org/OCA/website/jobs/166716308#L1157), so no need to block this PR.

2016-10-11 11:48 UTC, pedrobaeza approved these changes
Hi, that was what I want to hear. As the problem stated by @rafaelbn is fixed, I merge.

2016-10-11 11:48 UTC, merged