8.0 website blog tags variable dimension
OCA/website pull request #258
Opened 2016-09-21 15:38 UTC by gfcapalbo

Extends the tag cloud availiable in website_blog to support variable dimensions of the tags, based on the number of blogs they are contained in.

2016-09-21 16:00 UTC, hbrunn commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +            this.random_placement = random.choice([x for x in range(0, 4000)])
this is fantastically inefficient. Compare

```bash
$ python -m timeit 'import random; random.choice([x for x in range(0, 4000)])'
10000 loops, best of 3: 112 usec per loop
$ python -m timeit 'import random; random.randint(0, 4000)'
1000000 loops, best of 3: 1.07 usec per loop
```

and use https://docs.python.org/2/library/random.html#random.randint

2016-09-21 16:02 UTC, hbrunn commented on website_blog_tags_variable_dimension/static/src/js/website_blog_tags_variable_dimension.js
> +}
remove empty files (also the css file above)

2016-09-21 16:02 UTC, hbrunn commented on website_blog_tags_variable_dimension/views/templates.xml
> +                        <section class="mt32">
watch your indentation

2016-09-21 16:06 UTC, hbrunn commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +        return sorted(self, key=lambda x: x.random_placement)
I think you're better off replacing this by https://docs.python.org/2/library/random.html#random.sample (k = len(self)) and remove the function fields about randomness. As you only need them in your view, you're better off doing this in some function you call - this saves the field related overhead you don't need here

2016-09-21 16:07 UTC, hbrunn requested changes
and check https://travis-ci.org/OCA/website/jobs/161664244#L472

2016-09-21 16:07 UTC, hbrunn commented on website_blog_tags_variable_dimension/README.rst
> +* ...
remove empty sections

2016-09-21 16:07 UTC, hbrunn commented on website_blog_tags_variable_dimension/README.rst
> +* gfcapalbo <giovanni@therp.nl>
you might want to change this

2016-09-21 16:07 UTC, hbrunn commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +            this.max_ranking = float(max_ranking)
replace the loop by self.update()
But as this is probably called very often and we hopefully will have tens of thousands of posts in a while, I'd propose to make this field stored anyways

2016-09-21 16:07 UTC, hbrunn commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +            )
missing blank line

2016-09-21 16:07 UTC, hbrunn commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +            this.tag_cardinality = len(this.post_ids.ids)
also a case for a stored field

2016-09-22 09:08 UTC, gfcapalbo commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +            this.random_placement = random.choice([x for x in range(0, 4000)])
that means that al random selections even non integer ones should be done by hashtable that associates ints to values +randint  to harness the x10 factor improvement. i used random.sample for this and removed the whole field.

2016-09-22 09:10 UTC, gfcapalbo commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +            this.random_placement = random.choice([x for x in range(0, 4000)])
x100

2016-10-04 09:19 UTC, rafaelbn commented
Please @gfcapalbo could you check travis? thanks

2016-10-11 09:57 UTC, oscarolar commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +import random
import first standard imports [guideline](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#imports)

2016-10-11 10:00 UTC, oscarolar commented
what is the point of having this empty file?:
`website_blog_tags_variable_dimension/static/src/css/website_blog_tags_variable_dimension.css`

2016-12-05 23:02 UTC, susport commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +        tags = self.env['blog.tag'].search([])
Replace this code:
tags = self.env['blog.tag'].search([])
for tag in tags:

Suggestion:
for tag in self:

2016-12-05 23:05 UTC, susport commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +    def compute_color(self):
The compute methods start it with  _.
Example:  def _compute_color (self):

2017-01-06 16:27 UTC, gfcapalbo commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +        tags = self.env['blog.tag'].search([])
@susport, attention, this is a particular function.  "self" could be  any recordset , I need to actually scan all tags. this function has to return max cardinality amongst all records.. so unfortunately the more elegant  expression is not possible, the search needs to happen.

2017-01-06 16:27 UTC, gfcapalbo commented on website_blog_tags_variable_dimension/models/blog_tag.py
> +    def compute_color(self):
is this oca guideline?

2018-08-22 09:20 UTC, closed without merging