[MIG] website_disable_odoo
OCA/website pull request #274
Opened 2016-11-09 22:16 UTC by cubells

New module to remove odoo.com bindings on website

2016-11-09 22:16 UTC, cubells commented
cc @Tecnativa

2016-11-09 22:25 UTC, rafaelbn commented
Thanks! please check travis error

2016-11-10 08:37 UTC, Yajo commented
@cubells I'm pretty sure you should have created a separate git branch instead of making the PR directly from 9.0; just take note for future PR :wink:

2016-11-10 08:41 UTC, pedrobaeza commented on .travis.yml
> +      - ruby-sass
I think this is not a valid package. You have to put it in install part. But let's wait the result.

2016-11-10 08:43 UTC, cubells commented on .travis.yml
> +      - ruby-sass
@pedrobaeza  ok
@Yajo I saw it too late :(

2016-11-10 08:50 UTC, cubells commented
@pedrobaeza Travis failed on putting ruby-sass on install section.

2016-11-11 08:59 UTC, yajo requested changes

2016-11-11 08:59 UTC, Yajo commented on .travis.yml
> +  - ruby-sass
apt-get install ruby-sass

2016-11-11 09:02 UTC, Yajo commented
When you migrate an addon, you have to retrieve the commit history.

In case addon does not exist in branch: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8.0#how

And please put meaningful messages in commits.

2016-11-11 13:13 UTC, closed without merging