[10.0] Migrate website cookie notice
OCA/website pull request #309
Opened 2017-01-02 16:29 UTC by hurrinico

2017-01-02 17:10 UTC, pedrobaeza commented
Wow, what a huge commit quantity. Can you please squash by author and all the translation one together?

2017-01-03 09:34 UTC, hurrinico commented
depends on https://github.com/OCA/website/pull/310

2017-01-09 10:21 UTC, hurrinico commented
Hi @pedrobaeza i've made this pr following strictly [this guide](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0) and i think that all that commit comes from 9.0 version, so why squash them?.
I've to squash mine in one, but i'm waiting for pr310 to do that

2017-01-09 10:26 UTC, pedrobaeza commented
I know that you have followed the guide (and I have to reflect this somehow in the guide), but we don't need to keep such commit detail in this branch as the important part are the authors and the 9.0 part. For example, if during the 8.0 life cycle, you have retranslated 20 times the module terms, why keep all these diffs to increase a lot the branch size (and thus the download/pull size). We only need the last translation. The same can apply to the rest of the code, but with one exception: we must keep "final" code for each author.

2017-01-09 11:13 UTC, hurrinico commented
@pedrobaeza take a look if it's ok what i've made

2017-01-09 11:59 UTC, eLBati approved these changes
Once https://github.com/OCA/website/pull/310 is merged

2017-04-24 09:35 UTC, yajo requested changes

2017-04-24 09:35 UTC, Yajo commented on website_cookie_notice/views/website.xml
> +                <div class="col-xs-2 text-center">
Please include https://github.com/OCA/website/pull/333

2017-05-05 13:41 UTC, eLBati commented on website_cookie_notice/views/website.xml
> +                <div class="col-xs-2 text-center">
@Yajo added 22067cc5aa3d5ce43f6b0a8e6d73e99d18ede26d

2017-05-17 16:05 UTC, JonathanNEMRY commented
https://github.com/hurrinico/website/pull/2 before merge: add setuptools and use manifest instead of openerp

2017-06-30 09:23 UTC, yajo approved these changes

2017-06-30 09:24 UTC, Yajo commented
I added a commit to make it compatible with #353 when merged.

2017-06-30 09:33 UTC, Yajo commented
Rebased now that #353 is merged.

2017-06-30 09:36 UTC, pedrobaeza approved these changes
Merging when Travis finishes

2017-06-30 10:19 UTC, merged