[10.0][ADD] website_sale_line_total: Adds columns for unit price, total price
OCA/website pull request #315
Opened 2017-01-25 19:11 UTC by kellylougheed

- Creates a "Unit Price" column with the price for one unit
- Changes the "Price" column to show the actual total (quantity * unit price)

![website_sale_line_total](https://cloud.githubusercontent.com/assets/18649466/22305078/08e3200c-e2ef-11e6-8284-bf6c320cc8f2.png)

2017-01-25 20:13 UTC, pedrobaeza requested changes

2017-01-25 20:13 UTC, pedrobaeza commented on website_sale_line_total/README.rst
> +#. Go to ...
Fill this section

2017-01-25 20:13 UTC, pedrobaeza commented on website_sale_line_total/__manifest__.py
> +    "category": "Uncategorized",
Put correct category

2017-01-25 20:13 UTC, pedrobaeza commented on website_sale_line_total/__manifest__.py
> +    "license": "AGPL-3",
For website related modules it's interesting to put lgpl instead

2017-01-25 20:13 UTC, pedrobaeza commented on website_sale_line_total/views/website_sale_line_total_view.xml
> +        <xpath expr="//table[@id='cart_products']/thead/tr" position="replace">
Isn't possible to only add instead of replacing?  This nullify other addons that add things in this section.

2017-01-25 20:13 UTC, pedrobaeza commented on website_sale_line_total/views/website_sale_line_total_view.xml
> +        <xpath expr="//td[@name='price']" position="replace">
Hide it instead of replacing

2017-01-27 07:59 UTC, tarteo requested changes
Nice module! I tested the feature on runbot:

![image](https://cloud.githubusercontent.com/assets/10028499/22363910/00ecb720-e46e-11e6-91d9-ec90a213aedc.png)

The column that supposed to be Unit Price is titled Quantity.

2017-01-27 17:04 UTC, kellylougheed commented
Thanks for catching that @tarteo! It should appear as "Unit Price" now.

2017-01-30 07:53 UTC, tarteo approved these changes

2017-01-30 22:51 UTC, antoniocanovas approved these changes
LGTM, tested in runbot.

2017-03-09 18:54 UTC, lasley approved these changes
Thanks @kellylougheed

2017-03-09 18:55 UTC, merged