[ADD] website_sale_category_empty: Create module
OCA/website pull request #342
Opened 2017-05-17 00:33 UTC by tedsalmon

* Add module to hide categories that have no products associated with them
====================================
Website Sale - Hide Empty Categories
====================================

Removes any category links from the Shop which have no products associated
to them.

Usage
=====

Simply install the module and refresh your view. You will see the empty
categories disappear

cc @lasley

2017-05-17 01:10 UTC, lasley requested changes

2017-05-17 01:10 UTC, lasley commented on website_sale_category_empty/__manifest__.py
> +    ]
trailing comma

2017-05-17 01:10 UTC, lasley commented on website_sale_category_empty/models/product_public_category.py
> +        relation='product_public_category_product_template_rel',
Curious - why the explicit relation/col definitions? Are you hooking into a pre-existing join table?

2017-05-17 01:42 UTC, tedsalmon commented on website_sale_category_empty/models/product_public_category.py
> +        relation='product_public_category_product_template_rel',
Yes, I'm hooking into a pre-existing M2M relation -- This just made it bi-directional :)

2017-05-17 01:45 UTC, lasley commented on website_sale_category_empty/models/product_public_category.py
> +        relation='product_public_category_product_template_rel',
Sweet - can you add a note of the specific relation that you're hooking into please? This could be a pain point in migrations

2017-05-17 03:34 UTC, tedsalmon commented on website_sale_category_empty/models/product_public_category.py
> +        relation='product_public_category_product_template_rel',
I've made a note of this in the README :)

2017-05-17 03:42 UTC, lasley commented on website_sale_category_empty/models/product_public_category.py
> +        relation='product_public_category_product_template_rel',
I think a code comment would be more appropriate, directly above the field definition. As an engineer performing a migration, would you look in the ReadMe for this note while diagnosing a random issue with this field?

2017-05-17 07:28 UTC, pedrobaeza commented
Isn't better website_sale_hide_empty_category?

2017-05-17 23:42 UTC, tedsalmon commented
Good call, Pedro "Master of naming and reviews" Baeza ;P

2017-05-18 11:33 UTC, pedrobaeza approved these changes

2017-05-22 19:12 UTC, lasley approved these changes

2017-05-22 19:12 UTC, merged