[10.0][MIG] website_menu_multilang: Migration to 10.0
OCA/website pull request #352
Opened 2017-06-10 18:47 UTC by reinka

I ran all the commands in the migration guide however there wasn't any 9.0 commits.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

2017-06-12 08:29 UTC, yajo requested changes

2017-06-12 08:29 UTC, Yajo commented on website_menu_multilang/model/website.py
> +        default=_default_lang_ids
The common pattern is to declare fields on top, methods next.

Here you need then to use a `lambda self: self._default_lang_ids()` to be able to do that (which, in turn, is another requirement).

2017-06-12 08:29 UTC, Yajo commented on website_menu_multilang/view/website.xml
> -        <record id="menu_tree_inherit" model="ir.ui.view">
We all have likings about indentation, but please keep a smaller diff by respecting author's decision 😊

2017-06-16 20:11 UTC, reinka commented
@Yajo Done.

2017-06-19 08:19 UTC, yajo approved these changes
Reminder: squash at merge.

2018-10-02 09:37 UTC, simahawk requested changes

2018-10-02 09:37 UTC, simahawk commented on website_menu_multilang/__manifest__.py
>      'website': 'http://www.versada.lt',
https://github.com/OCA/website

2018-10-02 09:38 UTC, simahawk commented on website_menu_multilang/__manifest__.py
>      'website': 'http://www.versada.lt',
@reinka  can you fix this and squash on push? Then we can merge, tnx

2022-02-27 12:32 UTC, closed without merging