[MIG][web_editor_snippet_anchor] Migrate to v10
OCA/website pull request #361
Opened 2017-07-10 11:16 UTC by Yajo

All my own commits from v8 were squashed, module relicensed to LGPL, renamed to have `web_editor` prefix instead of `website`.

@Tecnativa

2017-07-10 11:20 UTC, pedrobaeza commented
Make the PR on OpenUpgrade for the renaming then.

2017-07-10 11:22 UTC, Yajo commented
The script is included, is it not needed here then?

2017-07-10 11:33 UTC, pedrobaeza commented
You need to put it on base module, because you need a "neutral ground" where declaring the renaming, or Odoo will say: I don't have `website_snippet_anchor` module. For pure renamings, you have to put it here: https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/addons/openupgrade_records/lib/apriori.py. For module merging operations, you have to put it on https://github.com/OCA/OpenUpgrade/blob/833bcee6670132ac410ab53dd0ffaa45ded1f43f/odoo/addons/base/migrations/10.0.1.3/pre-migration.py#L56

2017-07-10 14:37 UTC, chienandalu reviewed
@Yajo Couldn't make a functional review. Seems like runbot can't load the js:
![image](https://user-images.githubusercontent.com/5040182/28023359-07a358a2-658e-11e7-87de-f787b3383f87.png)

2017-07-12 07:31 UTC, pedrobaeza commented
@Yajo please check Travis status and make the migration script on OpenUpgrade repo.

2017-07-17 08:38 UTC, Yajo commented
I hope this update makes it work, and the migration script is now in https://github.com/OCA/OpenUpgrade/issues/964

2017-07-17 09:44 UTC, MiquelRForgeFlow requested changes
I think you should check the javascript files to make them compatible with the module

changing the .po files is optional  😜

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/templates/assets.xml
> +                src="/website_snippet_anchor/static/src/js/anchor_option.js"/>
web_editor

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/templates/assets.xml
> +                src="/website_snippet_anchor/static/src/js/link_dialog.js"/>
web_editor

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/static/src/js/link_dialog.js
> +        "/website_snippet_anchor/static/src/xml/link_dialog.xml");
web_editor

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/static/src/js/link_dialog.js
> +odoo.define("website_snippet_anchor.link_dialog", function (require) {
web_editor

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/static/src/js/anchor_option.js
> +odoo.define("website_snippet_anchor.anchor_option", function (require) {
web_editor

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/i18n/af.po
> +# * website_snippet_anchor
web_editor

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/i18n/af.po
> +#. module: website_snippet_anchor
web_editor

2017-07-17 09:44 UTC, mreficent commented on web_editor_snippet_anchor/static/src/js/anchor_option.js
> +        website = require("website.website"),
the module now doesn't depend on website

2017-07-18 07:46 UTC, Yajo commented
Very good catch @mreficent, I reverted the rename because this actually depends on website. Besides, not much sense of this outside a website environment.

2017-07-18 07:57 UTC, pedrobaeza commented
I'm afraid it's still red

2017-07-18 08:20 UTC, mreficent commented on website_snippet_anchor/templates/snippets.xml
> +<template id="snippet_options" inherit_id="web_editor.snippet_options">
website

2017-07-18 08:21 UTC, mreficent commented on website_snippet_anchor/templates/assets.xml
> +<template id="assets_editor" inherit_id="web_editor.assets_editor">
website

2017-07-18 08:21 UTC, mreficent commented on website_snippet_anchor/static/src/xml/link_dialog.xml
> +<t t-extend="web_editor.dialog.link">
website

2017-07-18 08:24 UTC, mreficent commented on website_snippet_anchor/static/src/js/anchor_option.js
> +        options = require("web_editor.snippets.options"),
website?

2017-07-18 08:24 UTC, mreficent commented on website_snippet_anchor/static/src/js/link_dialog.js
> +    var widget = require("web_editor.widget");
website?

2017-07-18 09:03 UTC, Yajo commented
@mreficent Sorry, none of your comments apply now.

@pedrobaeza There seems to be a problem installing sass, or compass, or bootstrap-sass, or I don't know what. @moylop260 could you check please here too?

2017-07-18 20:07 UTC, moylop260 commented
I have using [investigating-travis-test-failures](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#investigating-travis-test-failures) trick and the error that I found is *Cannot load compass. Maybe you should install the compass gem using this extra argument: $ sudo gem install compass --pre*:

```log

2017-07-18 20:05:13,175 2859 INFO moylop260 odoo.tests.common: phantom_run executing phantomjs /.repo_requirements/odoo/odoo/tests/phantomtest.js {"code": "odo
o.__DEBUG__.services['web_tour.tour'].run('website_snippet_country_dropdown_tour_demo_page')", "db": "moylop260", "session_id": "b93bc2d44ceb9e7a98a4081bc679cc
8c520675a9", "timeout": 60, "ready": "odoo.__DEBUG__.services['web_tour.tour'].tours.website_snippet_country_dropdown_tour_demo_page.ready", "url_path": "/", "
port": 18069}
2017-07-18 20:05:13,277 2859 INFO moylop260 odoo.addons.base.ir.ir_http: Generating routing map
2017-07-18 20:05:14,607 2859 WARNING moylop260 odoo.addons.base.ir.ir_qweb.assetsbundle: ERROR: Cannot load compass.
Maybe you should install the compass gem using this extra argument:

    $ sudo gem install compass --pre
This error occured while compiling the bundle 'web.assets_frontend' containing:
    - /web/static/lib/bootstrap/less/variables.less
    - /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less
    - /web/static/lib/bootstrap/less/mixins/buttons.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/utils.less
    - /web_editor/static/src/less/web_editor.variables.less
    - /web/static/src/less/import_bootstrap.less
    - /web_editor/static/src/less/web_editor.common.less
    - /website/static/src/less/website.ui.less
    - /website/static/src/less/website.ui.components.less
    - /website/static/src/less/website.wrapwrap.less
    - /website/static/src/less/website.snippets.less
    - /website/static/src/less/website.zoomodoo.less
    - /website_portal/static/src/less/website_portal.less
    - /website_blog/static/src/less/website_blog.less
    - /website_snippet_country_dropdown/static/src/css/style.sass
    - /website_form/static/src/less/website_form.less
```


I ran that command but the issue is not fixed.

@lasley Any clues?

2017-07-18 20:17 UTC, moylop260 commented
FYI current stable 10.0 branch is failing too:

Translation's build:
 - https://travis-ci.org/OCA/website/jobs/253901140 (3 days ago)

Previous build:
 - https://travis-ci.org/OCA/website/builds/252246305 (8 days ago)

The MQT changes was 12 days ago so is discard it.

Maybe  a odoo change breaking this library?

2017-07-19 09:59 UTC, Yajo commented
💚 😊

2017-07-19 10:12 UTC, MiquelRForgeFlow approved these changes

2017-07-19 10:14 UTC, chienandalu approved these changes
Finally tested on runbot! :+1:

2017-07-19 12:34 UTC, moylop260 approved these changes
Shouldn't squash fixup commits? (because is a migration)

2017-07-20 07:33 UTC, Yajo commented
Of course, I was waiting for approval before squashing, It's ready to merge now. Please somebody hit the button, it's ugly if I do it myself 😋

2017-07-20 07:34 UTC, pedrobaeza commented
Let CIs finish

2017-07-20 08:28 UTC, pedrobaeza commented
Travis is giving error now

2017-07-20 08:58 UTC, Yajo commented
Travis always tries surprises me.

- [Linter fails with `ImportError: No module named lxml`](https://travis-ci.org/OCA/website/jobs/255555596#L814).
- [`website_legal_page` test fails with 500 error](https://travis-ci.org/OCA/website/jobs/255555599#L1517). Hard to know who's to blame since current branch was broken due to https://github.com/OCA/maintainer-quality-tools/pull/465, which is fixed here but now reveals more problems.

Sorry to bother you again @moylop260 and @lasley, could you help here? It was green before the rebase...

2017-07-20 13:58 UTC, lasley commented
Worth mentioning - tests are only failing on `odoo/odoo`

2017-07-20 18:23 UTC, moylop260 commented
@Yajo FYI yesterday I noticed the `ImportError lxml` error but is a travis internal error.
More info about:
 - https://github.com/travis-ci/travis-ci/issues/8132 and https://github.com/OCA/maintainer-quality-tools/issues/467

2017-07-20 18:37 UTC, moylop260 commented
Build lint error is unrelated because my last comment above.
Build odoo/odoo was error because a change of odoo or a flaky error but I rebuilt and now is green.

Using runbot I tested just this module and don't show errors:
 - <img width="1264" alt="screen shot 2017-07-20 at 13 49 57" src="https://user-images.githubusercontent.com/6644187/28433228-791612d0-6d50-11e7-9c4d-16abc66b7bf2.png">

So I will merge it

2017-07-20 18:37 UTC, merged