[10.0][ADD] Markdown Block
OCA/website pull request #364
Opened 2017-07-17 12:38 UTC by Fuchur777

This module adds Markdown functionality to the frontend of Odoo Website Builder in the form of a Markdown block. https://en.wikipedia.org/wiki/Markdown

2017-07-17 13:12 UTC, astirpe commented
@Fuchur777 the installation of this module is failing:
`ImportError: No module named website_snippet_markdown`.

You have to add the file `__init__.py`, that is mandatory for an Odoo module, even if the file is empty.

2017-07-17 14:17 UTC, astirpe requested changes
I tested it and it works fine to me.
The `.js` files contained in the `locale` directory seem not loaded and they do not have any effect on the functionality, could they be removed from the module?

2017-07-17 14:17 UTC, astirpe commented on website_snippet_markdown/README.rst
> +   :target: http://www.gnu.org/licenses/agpl-3.0-standalone.html
According with the last template, the target link should be:
`   :target: http://www.gnu.org/licenses/agpl`

2017-07-17 14:17 UTC, astirpe commented on website_snippet_markdown/README.rst
> +5. Hit "Save"
Write numbered list by starting each line with `#. `, instead of writing numbers directly.
See [template](https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst)

2017-07-17 14:17 UTC, astirpe commented on website_snippet_markdown/README.rst
> +4. Write in Markdown of copy your markdown code
I think here the `of` should be `or` ... is it a typo?

2017-07-17 14:17 UTC, astirpe commented on website_snippet_markdown/__manifest__.py
> +    'author': 'Onestein',
Add OCA in the authors, see [manifest template](https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L10)

2017-07-17 14:17 UTC, astirpe commented on website_snippet_markdown/README.rst
> +
Please add also [this line](https://github.com/OCA/maintainer-tools/commit/a34d712a906c3a2db09953b746d7ee74180b296b):
`Do not contact contributors directly about support or help with technical issues.`
after the contributors list.

2017-07-18 07:03 UTC, tarteo requested changes

2017-07-18 07:03 UTC, tarteo commented on website_snippet_markdown/__manifest__.py
> +    'author': 'Onestein', 'Odoo Community Association (OCA)",
`'Onestein', 'Odoo Community Association (OCA)"` will not work, please use `"Onestein, Odoo Community Association (OCA)"` instead.

2017-07-18 07:03 UTC, Fuchur777 commented on website_snippet_markdown/__manifest__.py
> +    'author': 'Onestein', 'Odoo Community Association (OCA)",
Just did that, need coffee ;-)

2017-07-18 07:04 UTC, tarteo commented on website_snippet_markdown/__manifest__.py
> +    'author': 'Onestein', 'Odoo Community Association (OCA)",
This still applies after the latest (7467093) commit.

2017-07-18 07:05 UTC, tarteo commented on website_snippet_markdown/__manifest__.py
> +    'author': 'Onestein', 'Odoo Community Association (OCA)",
👍

2017-07-18 14:35 UTC, astirpe commented
[Frank Schellenberg](https://odoo-community.org/members/onestein-b-v-frank-schellenberg-1439) already signed the CLA but his login (@Fuchur777) seems unknown in OCA database.

2017-09-12 23:33 UTC, lasley commented
Added - CLA bot should be around in a bit to confirm

2017-09-12 23:33 UTC, lasley approved these changes

2017-09-12 23:39 UTC, lasley submitted a review, later dismissed
Oops I didn't mean to submit review quite yet. 

Travis failure looks unrelated. I think I've seen this in a few other PRs, including one of my own. Not sure of resolution yet.

Can you please add tests for the added functionality though? The code looks good and does seem to work on manual test 👍

2017-09-18 17:48 UTC, aldo774 commented
LGTM :+1:

2018-03-10 13:31 UTC, njeudy commented
@Fuchur777 I think it can depend from this OCA/web#738 ?

2018-10-02 09:42 UTC, simahawk requested changes
LG, small things to adjust

2018-10-02 09:42 UTC, simahawk commented on website_snippet_markdown/__manifest__.py
> +    'website': 'http://www.onestein.eu',
https://github.com/OCA/website

2018-10-02 09:42 UTC, simahawk commented on website_snippet_markdown/static/src/js/website_snippet_markdown.editor.js
> +});
missing newline

2018-10-02 09:42 UTC, simahawk commented on website_snippet_markdown/static/src/xml/website_snippet_markdown.xml
> +        <textarea data-provide="markdown" rows="10"></textarea>
wouldn't be better to wrap this into section or div w/ proper class?

2018-10-02 09:42 UTC, simahawk commented on website_snippet_markdown/templates/snippets.xml
> +</odoo>
same

2018-10-02 09:44 UTC, simahawk commented
@Fuchur777 would be nice to have some screenshots in the README :)

2022-02-27 12:32 UTC, closed without merging