add openstreetmap module
OCA/website pull request #386
Opened 2017-10-02 15:36 UTC by mFlayyan

2018-03-14 13:10 UTC, tarteo requested changes

2018-03-14 13:10 UTC, tarteo commented on website_openstreetmap/models/res_company.py
> +    """
Is this still needed or can it be removed?

2018-03-14 13:10 UTC, tarteo commented on website_openstreetmap/models/res_company.py
> +    _inherit = "res.partner"
This should be res.company right?

2018-03-14 13:10 UTC, tarteo commented on website_openstreetmap/models/res_company.py
> +                lat=self.partner_latitude or '',
If this is model is res.company then this should be self.partner_id.partner_latitude

2018-03-14 13:10 UTC, tarteo commented on website_openstreetmap/views/widget.xml
> +                <div name="openstreetmap_floating" class="o_block_image_float">
The standard way to define a snippet is like this:

`<t t-snippet="website.s_well" t-thumbnail="/website/static/src/img/blocks/block_well.png"/>`

`<template id="s_well" name="Well"></template>`

2018-10-01 12:00 UTC, simahawk commented
@mFlayyan still working on this?
I'm closing this as it's 1yr old and there's no answer to review.
Feel free to open it again if needed.
Thanks!

2018-10-01 12:00 UTC, closed without merging