[MIG] website_cookie_notice, website_legal_page: Migrated to 11.0
OCA/website pull request #408
Opened 2018-01-12 21:19 UTC by njeudy

- [MIG] website_cookie_notice: Migrated to 11.0
- [MIG] website_legal_page: Migrated to 11.0

2018-01-12 21:22 UTC, njeudy commented
Will only migratie cookie_notice in this because legal page already migrate In #403

2018-01-12 21:48 UTC, pedrobaeza commented
Please check Travis

2018-01-12 21:49 UTC, pedrobaeza commented
OK, I see it's because dependencies. Adding on the main comment.

2018-01-13 13:49 UTC, njeudy commented
Yes that's why I migrated both in same merge request :) but someone did it .. I will try to help review #403 :)

2018-01-23 08:20 UTC, simahawk requested changes

2018-01-23 08:20 UTC, simahawk commented on website_cookie_notice/__manifest__.py
> +    'version': '10.0.1.0.0',
11

2018-01-23 08:20 UTC, simahawk commented on website_cookie_notice/__manifest__.py
> +    'website': 'http://www.agilebg.com',
https://github.com/OCA/website

2018-01-23 08:20 UTC, simahawk commented on website_cookie_notice/__manifest__.py
> +    'auto_install': False,
you can drop this key

2018-01-23 08:20 UTC, simahawk commented on website_cookie_notice/controllers/__init__.py
> +# -*- coding: utf-8 -*-
remove coding headers from *.py

2018-01-23 08:22 UTC, simahawk commented
for the build: you can add oca_dependencies.txt with the branch where you've migrated ws legal page.

2018-01-23 15:32 UTC, njeudy commented
@simahawk I try to add oca_dependency.txt but:

fatal: Remote branch refs/pull/408/head not found in upstream origin
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 125, in <module>
    run(deps_checkout_dir, build_dir)
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 99, in run
    url, branch)
  File "/home/travis/maintainer-quality-tools/travis/clone_oca_dependencies", line 67, in git_checkout
    subprocess.check_call(command)
  File "/opt/python/3.5.4/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '-q', 'https://github.com/OCA/website', '-b', 'refs/pull/408/head', '--single-branch', '--depth=1', '/home/travis/dependencies/website']' returned non-zero exit status 128

Think I should wait for legal_page to be merged.

2018-01-23 18:21 UTC, simahawk commented
@njeudy the file is wrong :) you should provide the URL to your fork an put your branch, see https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/oca_dependencies.txt
Also, it's better to put temporary oca_dependencies.txt changes in a separated commit, like "DROP_ME_BEFORE_MERGE include pending PR" so that it's easier to spot it before merge and to roll it back. :wink:

2018-01-23 20:14 UTC, njeudy commented
@simahawk  Ok thanks

2018-01-24 09:25 UTC, simahawk approved these changes

2018-01-24 09:26 UTC, simahawk commented
@eLBati @Yajo ping :)

2018-01-24 10:34 UTC, Yajo commented
I'm waiting for #403

2018-01-26 11:31 UTC, pedrobaeza commented
Please rebase now that the dependency is merged.

2018-01-26 11:48 UTC, yajo approved these changes

2018-02-09 14:37 UTC, njeudy commented
@simahawk @Yajo can it be merged ?

2018-02-09 14:37 UTC, merged

2018-02-09 14:38 UTC, pedrobaeza commented
Yes, merging