10.0 port website canonical url to Odoo 10
OCA/website pull request #413
Opened 2018-02-01 10:33 UTC by zeroheure

I discovered Renka port after working on this. Anyway this one is complete. Readme updated also.

2018-02-01 16:48 UTC, zeroheure commented
It works. Travis fail because of another module in the tree.

2018-02-19 10:26 UTC, yajo requested changes
1. Keep git history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch
2. Fix travis, check [this error](https://travis-ci.org/OCA/website/jobs/337759890#L1329).
3. Thanks! 😊

2018-02-23 12:38 UTC, zeroheure commented
@Yajo Thanks. I've updated everything in another repository : zeroheure/website-canonical-url because I don't know how to do it here. I will create a new PR.

2018-02-23 12:42 UTC, pedrobaeza commented
@zeroheure you can simply overwrite current branch with that content with `push -f`

2018-02-23 20:35 UTC, zeroheure commented
@pedrobaeza Thanks, will try tomorow

2018-02-24 12:21 UTC, simahawk requested changes
some small things (beside commit history and travis)

2018-02-24 12:21 UTC, simahawk commented on website_legal_page/views/website_privacy.xml
>            inherit_id="website.layout_footer_copyright"
files committed by error? :)

2018-02-24 12:21 UTC, simahawk commented on website_canonical_url/models/__init__.py
> +# © initOS GmbH 2016
(c) -> Copyright

2018-02-24 12:21 UTC, simahawk commented on website_canonical_url/__manifest__.py
> +    'category': 'Website',
https://github.com/OCA/website

2018-02-24 12:43 UTC, zeroheure commented
@simahawk Thanks ! done for each file in github.com/zeroheure/website-canonical-url

2018-02-24 12:49 UTC, zeroheure commented
NB : I've added absolute url "in a light way" to not increase the server load. See views/template.xml :
`{{request.httprequest.url_root}}..{{canonical_url}}`
it results in URLS like "https://www.chez-les-enfants.fr/../shop" (note the `/../`) but it is valid in html.

2018-02-26 10:18 UTC, zeroheure commented
@Yajo The test case don't work any more and I don't know how to update it (I'm not a programmer). Could you help me (you wrote it) ?
Note that canonical url are now absolute while pager urls are relative.

2018-03-14 12:39 UTC, zeroheure commented
Please, I need help with code coverity because I don't understand the problem and how to solve it.
I think the requested changes are done.

2018-03-14 12:41 UTC, pedrobaeza commented
Code coverage is measuring the quantity of code that is covered against the one is not. In this case, there are less code covered, but I think it can be OK.

2018-03-14 12:57 UTC, zeroheure commented
@pedrobaeza Thanks.

2018-03-15 08:28 UTC, Yajo commented
Hi there, the git history problem is still there.

2018-03-16 17:28 UTC, pedrobaeza commented
@Yajo this is 10.0, so no full history is needed to be brought. Is there missing commit history in 9.0 that you have detected?

2018-03-20 09:55 UTC, Yajo commented
In this case it is needed because this addon was created before the 10.0 branch.

You can check that [none of these](https://github.com/OCA/website/commits/9.0/website_canonical_url) exist. Also 35b33727c128b1ec6908788164589eb9d30fb1f6 creates all files from scratch.

2018-03-20 13:44 UTC, zeroheure commented
@Yajo : I though the git history problem was solved (I've followed the docs you have pointed). As it looks difficult, it might be better to open a new PR following the right procedure and close this one ?

2018-03-21 08:22 UTC, yajo commented
It's not strictly necessary, you can do whatever changes you need to do, and then `git push --force` to this same branch; then the PR gets updated automatically.

2018-04-20 13:49 UTC, simahawk commented
@zeroheure @Yajo what's the status here? I need to migrate to v11 and I would start from here  :)

2018-04-20 13:50 UTC, simahawk commented
ah, history missing... I can handle that to speed it up

2018-04-20 14:01 UTC, zeroheure commented
@simahawk if you can help me it would be nice. I can't manage to add history.

2018-04-20 14:28 UTC, simahawk commented
replaced here https://github.com/OCA/website/pull/449

2018-04-20 14:28 UTC, closed without merging