[11.0][ADD] theme_flexible
OCA/website pull request #421
Opened 2018-02-09 10:24 UTC by tarteo

This theme is exceptionally configurable.
You can set the colors, fonts and layout you want (not limited by presets).

2018-02-09 10:27 UTC, pedrobaeza commented
Should we open OCA/website-themes?

Although official names start with theme_*, maybe we should use the naming convention website_theme_*. What do you think?

2018-02-09 10:45 UTC, Fuchur777 commented
Open an OCA theme repo.
Keeping with the oca naming convention sounds the way to go

2018-02-09 10:48 UTC, tarteo commented
_website_theme__ naming convention sounds good as there can also be _web_theme__ i guess.

2018-02-09 11:39 UTC, pedrobaeza commented
Yes, that's the case I was thinking in. And congratulations for bringing up the first OCA website theme module!

2018-02-12 07:05 UTC, jbeficent commented
@rgarnau can you review?

2018-02-12 12:35 UTC, rgarnau approved these changes
LGTM :+1:

2018-02-13 11:29 UTC, rgarnau reviewed
I've noticed that when using this theme if you press 'Customize > HTML/CSS Editor' the editor does not open.

2018-02-13 12:08 UTC, Fuchur777 commented
> I've noticed that when using this theme if you press 'Customize > HTML/CSS Editor' the editor does not open.
You are right. @tarteo

2018-02-13 15:52 UTC, tarteo commented
@rgarnau I fixed the bug, can you try again please?

2018-02-14 07:45 UTC, astirpe commented
```
FAIL: test_0_0_0_0 (odoo.addons.website_multi_theme.tests.test_assets.UICase)
` Check 0.0.0.0 downloads its default assets.
Traceback (most recent call last):
`   File "/home/travis/build/OCA/website/website_multi_theme/tests/test_assets.py", line 27, in test_0_0_0_0
`     "//head/link[contains(@href, 'web.assets_frontend')]"))
` AssertionError: [] is not true
FAIL: test_localhost (odoo.addons.website_multi_theme.tests.test_assets.UICase)
` Check localhost downloads its multiwebsite-enabled assets.
Traceback (most recent call last):
`   File "/home/travis/build/OCA/website/website_multi_theme/tests/test_assets.py", line 19, in test_localhost
`     'website_multi_theme.auto_assets_website')]"""))
` AssertionError: [] is not true
```

2018-02-14 10:53 UTC, rgarnau commented
@tarteo still not working!

2018-02-15 12:09 UTC, Fuchur777 commented
@tarteo @rgarnau 
Just tested the fix on Chrome / Firefox / Edge.
HTML/CSS editor appears as normal.

![image](https://user-images.githubusercontent.com/798891/36255993-62606eea-1251-11e8-8cc2-6bcb1a86dbbd.png)

2018-02-15 12:15 UTC, rgarnau commented
@Fuchur777 you're right - just checked again and it works just fine!

2018-02-16 11:28 UTC, Fuchur777 commented
@astirpe can you review to?

2018-03-01 10:09 UTC, astirpe requested changes
Could you fix the lint warnings?
https://travis-ci.org/OCA/website/jobs/342266796

2018-03-01 10:58 UTC, astirpe commented
Still some pylint warnings:

```
theme_flexible/static/src/js/theme_customize.js:127: [W7903(javascript-lint), ] 'SelectGoogleFontDialog' was used before it was defined. [Error/no-use-before-define]
theme_flexible/static/src/js/theme_customize.js:222: [W7903(javascript-lint), ] Missing radix parameter. [Error/radix]
theme_flexible/views/res_config_settings_view.xml:1: [W7908(missing-newline-extrafiles), ]  Missing newline
theme_flexible/README.rst:1: [W7908(missing-newline-extrafiles), ]  Missing newline
```

2018-03-01 12:23 UTC, astirpe approved these changes

2018-03-02 07:58 UTC, tarteo commented
@pedrobaeza Should I change the name to _website_theme_flexible_. Has it been decided yet?

2018-03-02 08:42 UTC, pedrobaeza commented
Yes, please, proceed with the renaming.

2018-03-07 10:20 UTC, tarteo commented
@pedrobaeza renamed the module.

2018-03-09 10:31 UTC, Fuchur777 commented
@pedrobaeza can it be merged?

2018-03-09 14:52 UTC, pedrobaeza commented
What do you think about the OCA/website-themes repository creation?

2018-03-09 15:04 UTC, tarteo commented
@pedrobaeza Sounds good!

2018-03-09 15:48 UTC, Fuchur777 commented
Sounds good to. Can you proceed with this @pedrobaeza ?

2018-03-09 17:54 UTC, pedrobaeza commented
Repository created, populated and configured in https://github.com/OCA/website-themes

2018-03-12 07:40 UTC, simahawk approved these changes
although there are bits that can be improved this is a good starting point for such feature. tnx! :)

2018-03-12 07:40 UTC, simahawk commented on theme_flexible/README.rst
> +Funders
This block should be used to mention external funders. I don't think you need it ;)

2018-03-12 07:40 UTC, simahawk commented on theme_flexible/models/theme_flexible.py
> +    google_query = fields.Char(compute='_compute_google_query')
don't you want to store this?

2018-03-12 07:40 UTC, simahawk commented on website_theme_flexible/templates/options/layout.xml
> +                        #wrap > * {
watch out w/ `*` selector, they are slow to render

2018-03-12 07:41 UTC, simahawk commented
please, squash before merging / moving to another repo

2018-03-12 09:35 UTC, pedrobaeza commented
Closing this one for moving it to OCA/website-themes

2018-03-12 09:35 UTC, closed without merging