[11.0] migrate website_odoo_debranding
OCA/website pull request #428
Opened 2018-02-27 03:44 UTC by ddufresne

2018-02-27 07:58 UTC, simahawk requested changes
small glitches

2018-02-27 07:58 UTC, simahawk commented on website_odoo_debranding/__init__.py
> +# -*- coding: utf-8 -*-
remove encoding from *.py

2018-02-27 07:58 UTC, simahawk commented on website_odoo_debranding/__manifest__.py
> +    "website": "https://www.tecnativa.com",
https://github.com/OCA/website

2018-02-27 07:58 UTC, simahawk commented on website_odoo_debranding/README.rst
> +.. image:: https://img.shields.io/badge/licence-LGPL--3-blue.svg
svg -> png (as svg is not supported in apps and images are not rendered)

2018-02-27 08:17 UTC, pedrobaeza commented
Check also existing warning:
```
2018-02-27 03:57:30,971 166 WARNING openerp_test odoo.addons.base.ir.ir_ui_view: Error-prone use of @class in view Remove Odoo Promotional Link (): use the hasclass(*classes) function to filter elements by their classes
2018-02-27 03:57:31,054 166 WARNING openerp_test odoo.addons.base.ir.ir_ui_view: Error-prone use of @class in view Remove Odoo Promotional Link (website_odoo_debranding.layout_footer_copyright): use the hasclass(*classes) function to filter elements by their classes
```

2018-02-28 02:50 UTC, ddufresne commented
@simahawk fixed

2018-02-28 07:30 UTC, simahawk approved these changes

2018-02-28 07:31 UTC, simahawk commented
@ddufresne sounds good. One last thing: squash your commits and reword to `[MIG][11.0] website_odoo_debranding` or similar. Tnx.

2018-02-28 08:40 UTC, rgarnau approved these changes
LGTM :+1:

2018-02-28 14:23 UTC, ddufresne commented
@simahawk @rgarnau @pedrobaeza thanks for the review. sqash done

2018-02-28 17:23 UTC, merged