[FIX] "Customize Theme" for theme_anelusia didn't' work
OCA/website pull request #436
Opened 2018-03-16 06:41 UTC by yelizariev

original method theme_customize_get returns view.xml_id, which are
'website_multi_theme.auto_view_ID_WEBSITE', while client works with original
IDs.

It leads to problem with, for example, theme_anelusia, because it has more than
one setting in its wizard. Without this commit it saves only one setting and
disable all other

2018-03-16 06:43 UTC, yelizariev commented
@Yajo one more  fix :wink:

2018-03-16 15:07 UTC, Railia approved these changes
I installed this updates, created a database without demo data. Then I installed Theme Anelusia eCommerce with dependencies.  Now everything works as it should.

2018-03-16 15:09 UTC, pedrobaeza requested changes
The override doesn't call super, breaking inheritability, so you have to find a way to keep both things (your change and the inheritability). Change also version number

2018-03-20 03:14 UTC, yelizariev commented
Updated: https://github.com/yelizariev/website/commit/ad6ffac09381c2b90579ac9a07431c4a79c1fdc0

2018-03-20 03:22 UTC, yelizariev commented
I thought sacrifice inheritability for the following reason:

* unlikely that someone needs to inherit this specific method
* it doubles the number of browsing \ searching

Both arguments are weak, though

2018-03-20 09:24 UTC, yajo approved these changes
Good catch!

2018-03-20 11:56 UTC, Railia commented
Seems it works

2018-03-20 11:56 UTC, Railia approved these changes
Seems it works

2018-03-20 12:01 UTC, pedrobaeza approved these changes

2018-03-20 12:01 UTC, merged