10.0 hotjar
OCA/website pull request #448
Opened 2018-04-18 15:56 UTC by lmgr0312

# **Hotjar analytics**
This module conect Odoo with Hotjar.
**http://hotjar.com**

_What is Hotjar?_ 
Hotjar is a way to truly understand the web and mobile site visitors with several tools that give us information from heatmaps, snapshot, etc.

![image](https://user-images.githubusercontent.com/17481201/38942312-14b404f8-42f4-11e8-9bd3-05d8edb1edf6.png)

# **Configuration**
To configure this module, you need to:

* Go to Website Admin/Configuration/Settings
* Fill in `Hotjar website ID`
* Take care that you fill in the correct value for `Hotjar website ID`

# **Usage**
To use this module, you need to:

* You only must configure the `Hotjar website ID`

2018-04-18 17:16 UTC, alan196 approved these changes
I have this module in production it works 👍

2018-04-20 12:46 UTC, tarteo requested changes
Thanks! Hotjar looks really interesting.

2018-04-20 12:46 UTC, tarteo commented on website_analytics_hotjar/README.rst
> +===============
Please add one '=' more :)

2018-04-20 13:24 UTC, HviorForgeFlow requested changes
Code Review LGTM :+1:

2018-04-20 13:24 UTC, hveficent commented on website_analytics_hotjar/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
.png instead of .svg

2018-04-20 14:34 UTC, lmgr0312 commented
@hveficent @tarteo 
The changes are already done!

Regards

2018-04-20 14:55 UTC, tarteo approved these changes
@lmgr0312 Thanks!

2018-04-20 16:38 UTC, HviorForgeFlow approved these changes

2018-04-21 11:02 UTC, pedrobaeza commented
Don't add plurals to the module name. I think `website_hotjar` as name can be enough. Os is there any other activity apart than analytics that Hotjar develops?

2018-04-22 15:19 UTC, simahawk requested changes

2018-04-22 15:19 UTC, simahawk commented on website_analytics_hotjar/__manifest__.py
> +    "summary": "Track website users using Hotjar",
`'website': 'https://github.com/OCA/website',`

2018-04-22 15:19 UTC, simahawk commented on website_analytics_hotjar/models/website.py
> +    hotjar_analytics_id = fields.Char(
I'd rename this field as `hotjar_analytics_[code|token|account|pick-yours]` to avoid clash w/ M2O fields convention.

2018-04-23 07:41 UTC, pedrobaeza commented on website_analytics_hotjar/models/website.py
> +    hotjar_analytics_id = fields.Char(
I insist in removing `analytics` part everywhere if it's not determinant.

2018-04-23 07:58 UTC, simahawk commented on website_analytics_hotjar/models/website.py
> +    hotjar_analytics_id = fields.Char(
to remove it from where? module name? If yes, I don't agree at all, as someone that is looking for addons that deal w/ "website analytics" is going to search using this wording and find them more easily.
We already have https://github.com/OCA/website/tree/11.0/website_analytics_piwik for instance.

If it's just about removing the trailing 's'.... still, I'd prefer to keep such module homogeneous.

Then, if you respect such assumptions is better to keep field names in lines as well.

My $0.02 :wink:

2018-04-23 08:00 UTC, pedrobaeza commented on website_analytics_hotjar/models/website.py
> +    hotjar_analytics_id = fields.Char(
out of everywhere: module name, variable names... `hotjar_id` instead of `hotjar_analytics_id`

2018-10-01 09:08 UTC, simahawk commented
@lmgr0312 any chance to get back on this??

2018-10-08 14:44 UTC, simahawk commented
@lmgr0312 I'm closing this since it seems your are not working on this. 
Feel free to re-open it if you want to continue, thanks.

2018-10-08 14:44 UTC, closed without merging