[FIX] duplicate creation must be done in correct order
OCA/website pull request #456
Opened 2018-05-01 15:48 UTC by yelizariev

After introducing sub-themes https://github.com/OCA/website/pull/454, it's essential to be sure that views are copied in a correct order. Imagine that Theme has two *theme-dependencies* where one depends (i.e. as in manifest) on another. In that case ``website.theme.asset`` records for those *theme-dependencies* can be created in a random order. It might lead to a mess when we copy firstly view that extends not-copied yet view from another *theme-dependency*.

2018-05-02 07:36 UTC, pedrobaeza commented on website_multi_theme/models/website_theme.py
> +    view_priority = fields.Integer(related='view_id.priority', store=True)
readonly=True

2018-05-03 23:20 UTC, pedrobaeza approved these changes

2018-05-14 11:23 UTC, yajo requested changes

2018-05-14 11:23 UTC, yajo commented on website_multi_theme/__manifest__.py
> +    "version": "10.0.1.3.3",
This implies database changes, so bump it to `1.4.0`

2018-05-15 11:42 UTC, yajo approved these changes

2018-05-15 12:03 UTC, pedrobaeza commented
There's a conflicting file.

2018-05-15 15:23 UTC, yelizariev commented
squashed and rebased :green_heart:

2018-05-15 15:29 UTC, merged