[11.0][website_product]
OCA/website pull request #459
Opened 2018-05-11 10:43 UTC by jbeficent

Website Product
===============

This module extends the functionality of the website to support viewing
a specific product that has been published.

With this module all products can potentially be published to the website.

Usage
=====

* Go to the Product form in the backend and press the button 'Unpublished On Website'.
  You will be redirected to the website, in the form view of that product.

* If the product is sealable the user will display the shopping options.
  Otherwise a simple form is displayed, with no option to purchase.

This module per se does not do more than that, and other modules such as
'cms_product_form' from the website-cms OCA repository make use of this module.

2018-06-11 09:29 UTC, Tardo commented on website_product/__manifest__.py
> +}
No author?

2018-07-02 20:59 UTC, Daemo00 commented
Please check Travis

2018-07-18 09:53 UTC, tarteo requested changes

2018-07-18 09:53 UTC, tarteo commented on website_product/controllers/__init__.py
> +from . import main
Please add new line (and in the other files)

2018-07-18 09:53 UTC, tarteo commented on website_product/models/product.py
> +        for product in self:
Can you change this to `self.filtered(lambda p: not p.sale_ok)` and remove the statement in the loop. I think it's a bit faster with many products.

2018-07-29 11:53 UTC, MeetKD requested changes

2018-07-29 11:53 UTC, MeetKD commented on website_product/__manifest__.py
> +}
website key is missing.

2018-08-02 08:15 UTC, hveficent commented
@tarteo @MeetKD @Tardo could you give a final review? Thanks in advance

2018-08-07 06:49 UTC, tarteo approved these changes

2018-08-07 07:09 UTC, pedrobaeza commented
I don't get the point about the module, and the description doesn't help. Can you extend the usage of it?

2018-10-01 10:05 UTC, simahawk requested changes

2018-10-01 10:05 UTC, simahawk commented on website_product/controllers/main.py
> +    # Do not use semantic controller due to SUPERUSER_ID
hmm I don't think you are using this approach :smile:

2018-10-01 10:05 UTC, simahawk commented on website_product/controllers/main.py
> +        if isinstance(product, request.env['product.template'].__class__):
you gonna get an empty recordset if prod not found: you can check for `product.exists`

2018-10-01 10:05 UTC, simahawk commented on website_product/controllers/main.py
> +            is_website_publisher = request.env['res.users'].has_group(
I'd split this perm check out

2018-10-01 10:05 UTC, simahawk commented on website_product/models/product.py
> +        super(ProductTemplate, self)._compute_website_url()
not needed to call super

2018-10-01 10:05 UTC, simahawk commented on website_product/models/product.py
> +        for product in self.filtered(lambda p: not p.sale_ok):
this way you loop twice: do the check inside the loop and do something like:
```
if prod.sale_ok:
    continue
```

2018-10-01 10:05 UTC, simahawk commented on website_product/security/ir.model.access.csv
> +website_product_product_template,product_template read,website_product.model_product_template,base.group_public,1,0,0,0
don't you need to read product.product too?

2018-10-01 10:05 UTC, simahawk commented on website_product/security/website_product.xml
> +        <field name="model_id" ref="product.model_product_template"/>
product.product too?

2018-10-01 10:05 UTC, simahawk commented on website_product/tests/test_website_product.py
> +        super(TestController, cls).setUp(*args, **kwargs)
pls block tracking for the whole test suite like:
```python
cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
```

2018-10-01 10:05 UTC, simahawk commented on website_product/tests/test_website_product.py
> +    @patch('odoo.http.request')
do you need to patch both?

2018-10-01 10:05 UTC, simahawk commented on website_product/views/website_product_templates.xml
> +        <div id="wrap">
class="product-[page|view]"

2018-10-01 10:05 UTC, simahawk commented on website_product/views/website_product_templates.xml
> +    <h1 class="col-md-12 text-center" id="product_name" t-field="product.name"/>
wrap it inside `<div class="product-detail" />`

2018-10-07 01:11 UTC, rafaelbn commented
Hello @jbeficent ! You get some comments in this PR. As is v11 I guess you are interested in continuing form merging :smile:  Thanks!

2018-10-08 11:21 UTC, HviorForgeFlow commented on website_product/models/product.py
> +        super(ProductTemplate, self)._compute_website_url()
It doesn't hurt

2018-10-08 11:21 UTC, HviorForgeFlow commented on website_product/__manifest__.py
> +}
Author and website key added

2018-10-08 11:21 UTC, HviorForgeFlow commented on website_product/security/ir.model.access.csv
> +website_product_product_template,product_template read,website_product.model_product_template,base.group_public,1,0,0,0
Added

2018-10-08 11:21 UTC, HviorForgeFlow commented on website_product/security/website_product.xml
> +        <field name="model_id" ref="product.model_product_template"/>
Added

2018-10-08 11:21 UTC, HviorForgeFlow commented on website_product/tests/test_website_product.py
> +    @patch('odoo.http.request')
They are not needed, removed.

2018-10-08 11:21 UTC, HviorForgeFlow commented on website_product/views/website_product_templates.xml
> +        <div id="wrap">
Added on div id="wrap". Is it correct? Would be better to create another div?

2018-10-08 11:22 UTC, HviorForgeFlow commented on website_product/views/website_product_templates.xml
> +    <h1 class="col-md-12 text-center" id="product_name" t-field="product.name"/>
Added

2018-10-08 11:22 UTC, HviorForgeFlow commented on website_product/tests/test_website_product.py
> +        super(TestController, cls).setUp(*args, **kwargs)
Added

2018-10-08 11:22 UTC, HviorForgeFlow commented on website_product/controllers/main.py
> +    # Do not use semantic controller due to SUPERUSER_ID
Just remove comment? Already done.

2018-10-08 11:24 UTC, HviorForgeFlow commented on website_product/controllers/main.py
> +        if isinstance(product, request.env['product.template'].__class__):
Added, review please

2018-10-08 11:24 UTC, HviorForgeFlow commented on website_product/controllers/main.py
> +            is_website_publisher = request.env['res.users'].has_group(
I don't get you, sorry.

2018-10-08 12:06 UTC, hveficent commented on website_product/models/product.py
> +        for product in self.filtered(lambda p: not p.sale_ok):
Added

2018-10-08 13:20 UTC, simahawk requested changes

2018-10-08 13:20 UTC, simahawk commented on website_product/controllers/main.py
> +        if product.exists:
this will be always true: you have to call it as it's a method ;)

2018-10-08 13:20 UTC, simahawk commented on website_product/controllers/main.py
> +            if product.website_published or self._is_website_publisher():
edit_page is for? Judging from the name I assume it should be there if `product.website_published` am I wrong?

2018-10-08 13:20 UTC, simahawk commented on website_product/models/product.py
> +        super(ProductTemplate, self)._compute_website_url()
yes as long it does not add any further computation... you are completely rewriting it so, IMO, there's no need nor benefit in calling it :nerd_face:

2018-10-08 13:20 UTC, simahawk commented on website_product/models/product.py
> +        for product in self.filtered(
you should remove 'filtered' now ;)

2018-10-08 13:20 UTC, simahawk commented on website_product/tests/__init__.py
> +from . import test_website_product
I don't care that much but.... linters will complain about not having this new line here

2018-10-08 13:20 UTC, simahawk commented on website_product/tests/test_website_product.py
> +    def setUpClass(cls, *args, **kwargs):
no  `*args, **kwargs`

2018-10-08 13:20 UTC, simahawk commented on website_product/tests/test_website_product.py
> +        self.assertTrue('request.render()' in str(response.name))
hmm you are not actually testing what's going to be rendered...
I'm not blocking but at least add a comment saying that we should test what's rendered (quite easy w/ lxml + xpath)

2019-05-06 07:55 UTC, hveficent commented
Superseed on #597
@jbeficent close it

2019-05-13 08:06 UTC, merged