[IMP] Add accepted_cookie cookie
OCA/website pull request #461
Opened 2018-05-15 09:44 UTC by wpichler

2018-05-15 23:58 UTC, rafaelbn reviewed
Waiting for runbot to test it. Travis is :red_circle:  Thanks @wpichler :smile:

2018-05-15 23:58 UTC, rafaelbn commented on website_cookie_notice/__manifest__.py
> +              "Callino"
I'm very thankful for you contribution and improvement of this module, but I'm not sure if is fair to add you as an author after 2 lines of code. Usually contributor it is.

2018-05-16 05:19 UTC, wpichler commented
Sorry - i thought this is necessary...

2018-06-14 07:24 UTC, tarteo commented
Hi @wpichler can you explain why this addition is needed, please?

2018-06-14 08:02 UTC, wpichler commented
there has been some rare cases where the normal way did not work - so setting this extra cookie does not hurt

2018-06-14 11:59 UTC, tarteo approved these changes

2018-10-07 01:13 UTC, rafaelbn commented
@Yajo could you please review this code changes?

2018-10-08 08:07 UTC, yajo requested changes
I like very much the idea, and IMHO this is much better implementation.

The problem with the previous one is that, when a session is destroyed (it is expired in the server, or user logs out), the user is asked yet again to allow cookies.

With this patch, the cookie acceptance is stored in a separate cookie, unrelated to user's session, so user shouldn't care about the cookie message anymore, no matter how many times he logs in or out.

(BTW, you should be the one explaining your work, not me, @wpichler :wink: )

But if we are going to use this new method, then please remove the old one. No need to have both.

2018-10-08 08:07 UTC, Yajo commented on website_cookie_notice/templates/website.xml
> +        not request.session.get('accepted_cookies') and not request.httprequest.cookies.get('accepted_cookies')"
Use only the new method to check cookie acceptance. Remove the old one please.

2018-10-08 08:51 UTC, wpichler commented
Sorry for not explaining - i'll try to explain better from now on...

Removing the old method is no problem - this would include removing the controller function...

While thinking about that - i'd had another idea to improve it...

* Add a new field "cookies_accepted" - Bool default false to res.partner
* When the cookie gets accepted - then call the controller function only if the current session is a non public session. 
* The controller function then does set the field cookies_accepted on the corresponding partner record
* On Template we do check for this field if it is already set or not

So registered users will get complete away from the cookie notice - also on different browsers / devices...

What do you think ?

2018-10-08 11:07 UTC, Yajo commented
Hmm I think that better not... :thinking:  I might accept cookies in my computer but not in my phone, for instance. I think the best choice is just the specific cookie as you were doing here.



> Removing the old method is no problem - this would include removing the controller function...

Please do! I :heart: code removal :yum:

2018-10-08 13:46 UTC, wpichler commented
Thats a valid point - so i've removed code now - and felling happy with it ;-)

2018-10-08 14:27 UTC, simahawk approved these changes
LG, thanks for the cleanup

2018-10-09 08:21 UTC, yajo approved these changes
Thanks! I rebuilt Travis; let's see if it goes :heavy_check_mark: now.

2018-10-10 07:00 UTC, simahawk commented
Tested on runbot, build is green: merging!
@wpichler thanks!

2018-10-10 07:00 UTC, merged

2018-10-11 16:38 UTC, pedrobaeza commented
Isn't this cookie notice deprecated since GDPR? If not, this should be forward-ported to v11

2018-10-11 18:08 UTC, wpichler commented
No - it has become more important since gdpr

2018-10-11 18:13 UTC, pedrobaeza commented
Well, I don't think so if you don't need any explicit consent. And for that, you need to modify current message. @Yajo, you are our GDPR expert. Can you talk about this?

2018-10-11 18:17 UTC, wpichler commented
I think it is needed - take a look here: https://eugdprcompliant.com/cookies-consent-gdpr/

2018-10-11 18:18 UTC, wpichler commented
Also - this is something that the website owner has to decide - we do only provide the tools for it

2018-10-11 18:21 UTC, pedrobaeza commented
> I think it is needed - take a look here: https://eugdprcompliant.com/cookies-consent-gdpr/

I remember that there was a clause that if the cookie is put for making legitimately work the website (not for tracking), it's not needed

> Also - this is something that the website owner has to decide - we do only provide the tools for it

Of course, but promoting something that is not useful at all is not the best way of optimizing flows. If we provide this module without more explanations on new legal topic, people will install it without knowing the real need.

2018-10-11 18:38 UTC, wpichler commented
Providing a explanation on a legal topic is in my opinion dangerous - if we are not correct with our interpretation of the topic - then we have given a wrong explanation.

2018-10-15 08:47 UTC, Yajo commented
This is part of [GDPR](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32016R0679), Article 6:

> Lawfulness of processing
> 1.   Processing shall be lawful only if and to the extent that at least one of the following applies:

> (a) the data subject has given consent to the processing of his or her personal data for one or more specific purposes;

> (b) processing is necessary for the performance of a contract to which the data subject is party or in order to take steps at the request of the data subject prior to entering into a contract;

So, if you want to use option B, you can skip this addon; but if you want to use option A, you can use it.

OCA is not your lawyer, we just share code here. If more than 1 user in the world wants option A, it makes sense to share this addon here. However, cnsult your lawyer to know whether to use it or not.