11.0 mig website_no_crawler
OCA/website pull request #471
Opened 2018-06-04 00:10 UTC by ernestotejeda

2018-06-04 07:39 UTC, simahawk requested changes

2018-06-04 07:39 UTC, simahawk commented on website_no_crawler/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
you could update READM according to new specs https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-06-04 07:39 UTC, simahawk commented on website_no_crawler/__manifest__.py
> +    'category': 'Website',
website: https://github.com/OCA/website

2018-06-04 07:39 UTC, simahawk commented on website_no_crawler/__manifest__.py
> +    'demo': [],
drop empty keys

2018-06-05 05:30 UTC, rafaelbn commented
cc @Tecnativa

2018-06-05 19:13 UTC, pedrobaeza approved these changes
I have also put the new README fragments + attend the comments.

2018-06-06 07:28 UTC, simahawk approved these changes

2018-06-06 07:30 UTC, chienandalu approved these changes

2018-06-06 07:31 UTC, yajo approved these changes

2018-06-06 07:31 UTC, merged