[IMP] website_sale_line_total: Add "Total price" column in the shoppi…
OCA/website pull request #492
Opened 2018-07-13 16:01 UTC by eantones

…ng cart lines at payment

Extends the functionality of website_sale_line_total by adding
separate columns for "Unit Price" and the total "Price"in the
shopping cart lines at payment.

2018-07-13 16:40 UTC, eantones commented
@kellylougheed @lasley  @pedrobaeza 
I'm looking forward to your comments
Thank you very much

2018-10-01 09:16 UTC, simahawk commented
@eantones tnx for you contrib. I think this belongs to https://github.com/OCA/e-commerce

2018-10-06 23:44 UTC, rafaelbn commented
hi @eantones ! Thanks for this contribution. You should move the PR to https://github.com/OCA/e-commerce as @simahawk said

We will review there

Thanks!

2018-10-11 17:27 UTC, pedrobaeza commented
Closing meanwhile.

2018-10-11 17:28 UTC, pedrobaeza commented
Hey, wait, this module is already here, and this is a bugfix/improvement. It should be moved for next versions. Reopening. @simahawk @rafaelbn please review.

2018-10-12 07:56 UTC, simahawk requested changes

2018-10-12 07:56 UTC, simahawk commented on website_sale_line_total/views/website_sale_line_total_view.xml
> +        <xpath expr="//table[@id='cart_products']/tbody/tr/td[span[contains(@t-field,'line.price_reduce_tax')]]" position="attributes">
not sure this is correct: 
1. it selects multiple elements
2. it applies an ID to something that is within a loop -> it should be a class

2018-10-12 07:56 UTC, simahawk commented on website_sale_line_total/views/website_sale_line_total_view.xml
> +        <xpath expr="//table[@id='cart_products']/tbody/tr/td[div[contains(@t-esc,'line.product_uom_qty')]]" position="attributes">
same

2018-10-12 07:56 UTC, simahawk commented on website_sale_line_total/views/website_sale_line_total_view.xml
> +        <xpath expr="//table[@id='cart_products']/thead/tr/th[@width='120']" position="before">
this is a poor selector IMO: are you selecting the one containing "Quantity"?
If yes: either you select by position or by text content.

2018-10-12 07:56 UTC, simahawk commented on website_sale_line_total/views/website_sale_line_total_view.xml
> +        <xpath expr="//td[@id='td-unit_price']" position="attributes">
are you selecting something that you just added?

2018-10-12 07:56 UTC, simahawk commented on website_sale_line_total/views/website_sale_line_total_view.xml
> +        <xpath expr="//table[@id='cart_products']/tbody/tr/td[span[contains(@t-field,'line.price_reduce_tax')]]" position="attributes">
OMG, they did it wrong https://github.com/odoo/odoo/blob/10.0/addons/website_sale/views/templates.xml#L868
Not a good reason to replicate the error tho... no? :)

2022-04-24 12:36 UTC, closed without merging