[ADD] Added new module website_seo_product
OCA/website pull request #521
Opened 2018-10-04 10:59 UTC by wpichler

Does integrate website_seo_redirect directly with products

2018-10-04 11:17 UTC, nikul-serpentcs reviewed
Improve Code

2018-10-04 11:17 UTC, nikul-serpentcs commented on website_seo_product/__manifest__.py
> +    "external_dependencies": {
@wpichler If not any `external_dependencies` then remove a key.

2018-10-04 11:17 UTC, nikul-serpentcs commented on website_seo_product/__manifest__.py
> +    "demo": [
same here

2018-10-04 11:17 UTC, nikul-serpentcs commented on website_seo_product/__manifest__.py
> +    "qweb": [
same here

2018-10-04 11:17 UTC, nikul-serpentcs commented on website_seo_product/models/product.py
> +            product.seo_path = product.seo_redirect_id.destination if product.seo_redirect_id else product.website_url
It's too long line

2018-10-04 11:17 UTC, nikul-serpentcs commented on website_seo_product/models/product.py
> +            product.website_url = product.seo
Add new Blank line

2018-10-04 11:17 UTC, nikul-serpentcs commented on website_seo_product/views/product.xml
> +</odoo>
Add new Blank line

2018-10-04 11:17 UTC, nikul-serpentcs commented on website_seo_product/views/product.xml
> +    <data>
Remove it

2018-10-04 13:33 UTC, wpichler commented
all done.
I am curios what is happening all the time with my newlines - pycharm seems to remove the last newline at every file - i do have to add 2 newlines - to get 1 newline at file end on real file...

2018-10-04 17:36 UTC, wpichler commented
I've reworked the functionality a little bit - module does now support renaming of product without losing the seo url !

2018-10-06 23:05 UTC, rafaelbn commented
Hello @wpichler !

Thanks!.

Have you read https://www.odoo.com/documentation/user/10.0/website/optimize/seo.html ?
I'm not sure in v12 hace improvements : https://www.odoo.com/documentation/user/12.0/website/optimize/seo.html ?

Note than in Odoo v12 you can rename URLs.

I set WIP until runbot :red_circle: and travis :red_circle: gets :green_heart: 

Ping @cristinamartinrod @Yajo what do you think?

2018-10-08 08:01 UTC, yajo requested changes
Yikes! I'm very sorry to say this... :sweat_smile: but I think this module is wrong by design: `website_seo_redirection` uses 301 redirections by default. A 301 redirection is correctly handled by web crawlers (by indexing only the target url) and browsers (by caching the redirection and not asking for it more than once), so basically you shouldn't care at all about what this module is caring about.

So, IMHO, this addon adds no value to current implementation, although it adds complexity and reduces maintainability. We shouldn't merge this. :roll_eyes:

2018-10-08 08:07 UTC, cristinamartinrod requested changes
I think that this module is necessary in v10 but it can has complications if any ecommerce wants to migrate to v12. Anyway in this case, only changes the URL visible in the browser but keeps canonical URL, so if you want to have "pretty" url's for the user it's ok, but if you want a new url more seo-friendly, then the canonical (the only one that crawls google) should be modified.

2018-10-08 08:11 UTC, wpichler commented
I do not agree here. First of all - this module is not about using 301 vs using internal redirect. This module does just help the user when the user does change the product name - to update the redirect rule according to the name change.

Behaviour without this module:
There is a Product named "Apple" with ID 3 - so path to product is /shop/product/Apple-3. User does now create a seo redirect rule (using 301 or internal does not matter here). So that /fruit/apple does point to /shop/product/Apple-3.
Now the user decides to rename the product to "Organic Apple" - because of this the url will change to /shop/product/OrganicApple-3.
So the existing redirect rule will not work anymore.

Behaviour with this module:
If the product name changes - it will update the seo rule to the new url.

2018-10-08 08:12 UTC, wpichler commented
And about 301 vs internal redirect - as far as i know (correct me when i am wrong) - you will get better ranking when not using 301.

2018-10-08 11:03 UTC, Yajo commented
@wpichler:

>  If the product name changes - it will update the seo rule to the new url.

AFAICS the current code in this PR is buggy and will not do that, if that was indeed the intention, because the search for origin URL is made after the actual product write, which means it will never find a result.

> Now the user decides to rename the product to "Organic Apple" - because of this the url will change to /shop/product/OrganicApple-3.
> So the existing redirect rule will not work anymore.

AFAIK the redirect rule will still work, just with 1 extra step (automatic and transparent to the user/crawler), because Odoo uses in reality only the "3" part at the end; the rest of the slug is just aesthetic, and will be autoredirected by odoo if wrong, as you see in core v10 runbot:

![peek 08-10-2018 11-47](https://user-images.githubusercontent.com/973709/46605044-12224e00-caf0-11e8-8c0c-e6573c8313ab.gif)


> as far as i know (correct me when i am wrong) - you will get better ranking when not using 301

See the [Google support page on the matter](https://support.google.com/webmasters/answer/93633?hl=en). Quoting it:

> If you need to change the URL of a page as it is shown in search engine results, **we recommend** that you use a server-side 301 redirect. **This is the best way** to ensure that users and search engines are directed to the correct page. The 301 status code means that a page has permanently moved to a new location.

So, using 301 redirections is actually a Google recommendation for our use case at hand.

---

@cristinamartinrod:


> if you want a new url more seo-friendly, then the canonical (the only one that crawls google) should be modified

You are absolutely right. We have [`website_canonical_url`](https://github.com/OCA/website/tree/10.0/website_canonical_url), but it does not have any link or compatibility layer with `website_seo_redirection`. Support could be added there directly on a lazy-dependency fashion, or we could just leave it as it is and add support in v11 directly, where redirections are a core feature (although still the canonical URL is a core problem that should be instead handled by Odoo directly and automatically).

---

Summarizing, still I get to the same conclusion as before: this PR is not needed.

On behalf of being practical, I'm gonna close the PR, but please reopen if you still think I'm wrong (which might be true indeed), or if you still want to wait for others' opinions :wink:. Thank you very much for the contribution!

2018-10-08 11:03 UTC, closed without merging