[ADD] Added website_seo_public_category
OCA/website pull request #522
Opened 2018-10-04 14:04 UTC by wpichler

2018-10-06 22:58 UTC, rafaelbn commented
Hello @wpichler ! Thanks for this contribution.

I don't know how to test it. Please could you add to the usage section how can I test this module in runbot please? https://github.com/OCA/website/pull/522/files#diff-4e091c6cc99b8e68eb94d01ab846edc3R3

Also you should review runbot :red_circle: and travis error please :red_circle: 

Ping me when done please. Thanks! :smile:

2018-10-06 23:00 UTC, rafaelbn commented
Ping @cristinamartinrod @Yajo @chienandalu

2018-10-08 13:09 UTC, chienandalu requested changes
Couldn't make it work in runbot:

#. Created a redirection
#. Changed the category name
#. The change wasn't propagated to the redirection...

Review minor LINT errors as well

2018-10-08 13:09 UTC, chienandalu commented on website_seo_public_category/readme/USAGE.rst
> +* Create a Product Categorie
s/categorie/category

2018-10-08 13:09 UTC, chienandalu commented on website_seo_public_category/readme/USAGE.rst
> +* Product Categorie will be available in shop under the path /shop/categorie/name-ID
s/categorie/category

2022-05-29 12:39 UTC, closed without merging