Fix icon anchor scroll
OCA/website pull request #541
Opened 2018-11-26 15:25 UTC by Ricardlol

fix plugin in this situation:
```html
<a href="#aplicacio" class="btn btn-default">
    <span class="fa fa-suitcase fa-5x __web-inspector-hide-shortcut__" data-original-title="" title="" style=""></span>
</a>
```

2018-11-27 09:36 UTC, Yajo commented
Can you explain better on what are you fixing, how to reproduce the error, etc.?

2018-12-15 10:44 UTC, Ricardlol commented
Sorry by not answer,
The mistake is that the anchor doesn't work with images, icons, etc, only
work with strings by reproduce the error create a image or icon and add a
anchor
example:
<a href="#example">
    <img src="example.png" alt="example">
</a>

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

El mar., 27 nov. 2018 a las 10:36, Jairo Llopis (<notifications@github.com>)
escribió:

> Can you explain better on what are you fixing, how to reproduce the error,
> etc.?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/website/pull/541#issuecomment-441990823>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AiyMLkLysWIXQ2ZuFCohQM44sChkD_Xxks5uzQeLgaJpZM4YzQIL>
> .
>

2018-12-17 10:59 UTC, yajo requested changes

2018-12-17 10:59 UTC, Yajo commented on website_anchor_smooth_scroll/static/src/js/website_anchor_smooth_scroll.js
> +        var anchor_fragment = event.target.hash || this.hash;
Change to `event.currentTarget.hash`

2018-12-18 15:35 UTC, tarteo requested changes
Can you increase the version number in the manifest.

2022-06-12 12:35 UTC, closed without merging