[IMP] 11.0 website_form_recaptcha improve JS
OCA/website pull request #556
Opened 2019-01-04 13:30 UTC by mpanarin

* Make JS easier to extend (for example, when captcha api params are required)
* Make enforce language when possible (auto-detect can fail if browser lang is different)

2019-01-04 14:02 UTC, simahawk requested changes
version upgrade missing.
If you add the lang improvement you should also mention it in README

2019-01-04 14:02 UTC, simahawk commented on website_form_recaptcha/static/src/js/field_recaptcha.js
> +            return 'https://www.google.com/recaptcha/api.js';
I'd set `hl=session.user_context.lang` if available

2019-01-04 14:25 UTC, mpanarin commented on website_form_recaptcha/static/src/js/field_recaptcha.js
> +            return 'https://www.google.com/recaptcha/api.js';
I think the default parameters of api should be kept by default. This way, `_get_captcha_script_url` is easy to extend. So, I think its better to keep it as is.

2019-01-04 14:47 UTC, simahawk commented on website_form_recaptcha/static/src/js/field_recaptcha.js
> +            return 'https://www.google.com/recaptcha/api.js';
well, to me if the language in the captcha is not loaded properly based on the odoo lang... then it's a bug, not a feature.
Unless you show me the contrary... :wink: 
In my case, with the website in FR and my browser in EN I got captcha content in EN, which is wrong IMO.

2019-01-08 12:23 UTC, simahawk reviewed
LG, minor adjustments

2019-01-08 12:23 UTC, simahawk commented on website_form_recaptcha/static/src/js/field_recaptcha.js
> +            if (this.captcha_languages.includes(lang)) {
I'd move `'https://www.google.com/recaptcha/api.js'` to a static attribute `recaptcha_js_url` and keep only `_get_captcha_script_url`.

Also, I'd add 2 comments inside the IF blocks: `// lookup for specific localization (ie: fr-FR)` and `// fallback to main lang`

2019-01-08 13:35 UTC, yajo approved these changes
I :heart: it.

2019-01-08 20:33 UTC, pedrobaeza requested changes

2019-01-08 20:33 UTC, pedrobaeza commented on website_form_recaptcha/README.rst
> +browser.
Missing extra line

2019-01-08 20:33 UTC, pedrobaeza commented on website_form_recaptcha/README.rst
> +Captcha will try to use the language of your website, if it, for whatever
```suggestion
Captcha will try to use the language of your website. If it, for whatever
```

2019-01-08 20:33 UTC, pedrobaeza commented on website_form_recaptcha/README.rst
> +reason, can't find it will default it google api and use a language of the
```suggestion
reason, can't find, it will default to google API and use the language of the
```

2019-01-09 08:14 UTC, simahawk approved these changes

2019-01-09 08:15 UTC, simahawk commented
@pedrobaeza your comments attended

2019-01-09 08:40 UTC, merged