[12.0][MIG] website_media_size: Migration to v12
OCA/website pull request #595
Opened 2019-05-04 21:54 UTC by keylor2906

- Improve adding state colors depending on file size

2019-05-06 17:12 UTC, tbaden requested changes
please use the fragmented readme.
for more [information](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0)

2019-05-06 20:20 UTC, tbaden requested changes
thanks for the work 👍 
please keep the commit history. For more info see [this](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0)

2019-05-06 20:20 UTC, tbaden commented on website_media_size/static/src/scss/website_media_size.scss
> +}
missing newline

2019-06-05 14:29 UTC, oscarolar commented
@keylor2906 can you please address the comments of this PR?

2019-06-05 14:56 UTC, keylor2906 commented on website_media_size/static/src/scss/website_media_size.scss
> +}
Added line at EOF

2019-06-05 14:58 UTC, keylor2906 commented
Added the fragmented readme and keep the commit history

2019-06-05 16:08 UTC, oscarolar approved these changes
Tested in runbot, works as expected 
![image](https://user-images.githubusercontent.com/3836433/58972047-4551d580-8782-11e9-9771-911afbe58fd4.png)

2019-06-09 20:22 UTC, tbaden approved these changes

2019-06-09 21:24 UTC, merged