[FIX][11.0][WIP] website_form_builder travis warning
OCA/website pull request #614
Opened 2019-05-08 18:30 UTC by tbaden

issue https://github.com/OCA/website/issues/603 : 
fix of:
************* Module website_form_builder
website_form_builder/static/src/js/tour.js:11: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_form_builder/static/src/js/tour.js:15: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
website_form_builder/static/src/js/tour.js:20: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:21: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:22: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:23: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:24: [W7903(javascript-lint), ] Expected indentation of 8 spaces but found 4. [Error/indent]
website_form_builder/static/src/js/tour.js:25: [W7903(javascript-lint), ] Expected indentation of 8 spaces but found 4. [Error/indent]
website_form_builder/static/src/js/tour.js:26: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:27: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:28: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:29: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:30: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:31: [W7903(javascript-lint), ] Line 31 exceeds the maximum line length of 80. [Error/max-len]
website_form_builder/static/src/js/tour.js:31: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:32: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:33: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:34: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:35: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:36: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:37: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:38: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:39: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:40: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:41: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:42: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:43: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:44: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:45: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:46: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:47: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:48: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:49: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:50: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:51: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:52: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:53: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:54: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:55: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:56: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:57: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:58: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:59: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:60: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:61: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:62: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:63: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:64: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:65: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:66: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:67: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:68: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:69: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:70: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:71: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
website_form_builder/static/src/js/tour.js:72: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:73: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
website_form_builder/static/src/js/tour.js:74: [W7903(javascript-lint), ] Expected indentation  [...]

2019-05-09 08:05 UTC, yajo requested changes
Still some errors: https://travis-ci.org/OCA/website/jobs/530023787#L743-L754

2019-05-09 08:45 UTC, tbaden commented
still WIP, will check this later today

2019-05-09 18:30 UTC, tbaden commented
@Yajo are you using eslint by any chance?

2019-05-09 21:20 UTC, tbaden commented
@Yajo is this the correct param type to use here?
https://github.com/OCA/website/blob/9345c961e6a98b7d121c3bd5a930d659760260e0/website_form_builder/static/src/js/snippets.js#L28

2019-05-10 08:00 UTC, yajo requested changes
Please abstain from changing unnecessary things:

- Multiple variable declarations in one statement.
- Single vs double quotes.
- Multiline dicts with a single key.

Just remove the warnings, but don't apply changes that are not required for that please. The git history is helpful to review why things changed, so reducing the diff is helpful for maintenance.

2019-05-10 08:00 UTC, Yajo commented on website_form_builder/static/src/js/snippets.js
> +                    async: false,
```suggestion
                    "async": false,
```

This is a reserved word in modern JS.

2019-05-10 08:00 UTC, Yajo commented on website_form_builder/static/src/js/snippets.js
> +                );
```suggestion
            );
```

2019-05-10 21:36 UTC, tbaden commented
done

2019-05-13 07:47 UTC, yajo approved these changes

2019-05-13 07:52 UTC, yajo requested changes

2019-05-13 07:52 UTC, Yajo commented on website_form_builder/static/src/js/snippets.js
> +     * @param {Class} servicesMixin
In JS there are no classes; they are `Object`s.

```suggestion
     * @param {Object} servicesMixin
```

2019-05-13 07:52 UTC, Yajo commented on website_form_builder/static/src/js/snippets.js
> +     * @param {Class} servicesMixin
```suggestion
     * @param {Object} servicesMixin
```

2019-05-13 17:50 UTC, tbaden commented
done

2019-05-15 07:53 UTC, yajo approved these changes

2019-05-15 07:53 UTC, merged