[13.0][MIG] website_media_size
OCA/website pull request #679
Opened 2020-01-09 15:53 UTC by tarteo

2020-05-18 15:35 UTC, Tardo requested changes
Thanks for the work

2020-05-18 15:35 UTC, Tardo commented on website_media_size/static/src/js/website_media_size.js
> +    var MediaModules = require('wysiwyg.widgets.media');
```suggestion
    const MediaModules = require('wysiwyg.widgets.media');
```

2020-05-18 15:35 UTC, Tardo commented on website_media_size/static/src/js/website_media_size.js
> +    var ImageWidget = MediaModules.ImageWidget;
```suggestion
    const ImageWidget = MediaModules.ImageWidget;
```

2020-05-18 15:35 UTC, Tardo commented on website_media_size/static/src/xml/website_media_size.xml
> +                <span t-attf-class="o_existing_attachment_size #{file_size > 999 and 'o_existing_attachment_size_danger' or file_size > 99 and 'o_existing_attachment_size_warning' or ''}"><t t-esc="f
I don't like these hard-coded values (999 and 99)... and units are not correct, for me better use "KiB".

2020-05-18 15:35 UTC, Tardo commented on website_media_size/templates/assets.xml
> +                  type="text/scss" rel="stylesheet"/>
```suggestion
                  type="text/css" rel="stylesheet"/>
```

2021-03-30 15:13 UTC, claudiagn reviewed
@tarteo can you provide a module description so I can review please? thx 👍

2022-10-16 12:50 UTC, closed without merging