[13.0][MIG] website_cookie_notice: Migration to 13.0
OCA/website pull request #713
Opened 2020-04-14 10:11 UTC by Tardo

cc @tecnativa TT19839

2020-04-14 11:12 UTC, chienandalu requested changes
- pre-commit failing
- When I click the "Ok" button, the cookies message doesn't go away

2020-04-14 17:48 UTC, Tardo commented
Fixed, thanks! the pre-commit warnings are no related with this module... but i added another "[IMP] black, isort, prettier" commit to solve it.

2020-04-15 07:04 UTC, chienandalu reviewed
I observe this weird behavior:
![cookies-message-reappears](https://user-images.githubusercontent.com/5040182/79307925-faebca00-7ef7-11ea-8a1d-c69765f2efa4.gif)
Shouldn't the preference be persistent?

2020-04-15 10:01 UTC, Tardo commented
Ummm yes by code this is store on the session cookie... i don't know if is best store it on a persistent cookie. ¿What happens with public users on a shared computer if we store it on a persistent cookie?

2020-04-15 10:03 UTC, pedrobaeza commented
Better to keep it this way as Odoo integrates it in v14

2020-04-15 10:16 UTC, chienandalu approved these changes
Ok, fine. It's annoying but I guess it's been like that until now

2020-04-15 10:32 UTC, pedrobaeza approved these changes

2020-04-15 10:33 UTC, pedrobaeza requested changes

2020-04-15 10:33 UTC, pedrobaeza commented on .isort.cfg
> +known_third_party=setuptools
Oh, wait, you mustn't change this!! Have you rebased?

2020-04-15 11:26 UTC, Tardo commented
Ok, hope now is ready.

2020-04-21 17:49 UTC, Tardo commented
This PR need review

2020-05-05 06:30 UTC, chienandalu commented
I guess only @pedrobaeza blessing is left

2020-05-05 06:53 UTC, pedrobaeza approved these changes

2020-05-05 06:53 UTC, pedrobaeza commented
/ocabot merge nobump

2020-05-05 07:49 UTC, merged