[IMP] website_snippet_country_dropdown: readonly mode
OCA/website pull request #720
Opened 2020-05-13 09:52 UTC by Yajo

- Remove some garbage code.
- Add readonly mode.
- Add demo data.
- Improve tour.

@Tecnativa TT17694

2020-05-14 14:00 UTC, pedrobaeza approved these changes

2020-05-14 14:25 UTC, Tardo requested changes
Looks Good! I think that you can remove all related with "this.$country_code"

2020-05-15 09:48 UTC, Yajo commented
> I think that you can remove all related with "this.$country_code"

I think it's still useful. As it is right now, 3 fields are submitted in the form: full text, country code alone, vat alone. It seems the easiest way to support any use case downstream. Besides, that could potentially break backwards compatibility quite badly. Maybe we could consider that when migrating, but I don't really see a big benefit TBH. :thinking:

2020-05-18 08:22 UTC, Tardo commented
@Yajo I can't found where 'js_country_code' is defined...

2020-05-18 08:29 UTC, Yajo commented
Ooh yes, understood. Removed now. Thanks!

2020-05-18 11:22 UTC, Tardo approved these changes
:+1:

2020-05-18 11:43 UTC, pedrobaeza commented
/ocabot merge minor

2020-05-18 12:44 UTC, merged