[12.0][ADD] website_megamenu
OCA/website pull request #726
Opened 2020-05-25 15:11 UTC by Tardo

Backport of 'mega menu' feature from 13.0 CE

![megamenu](https://user-images.githubusercontent.com/731270/82824913-8159db00-9eaa-11ea-9374-d8b3dbfc8709.gif)

cc @tecnativa TT20965

2020-05-26 07:19 UTC, sergio-teruel approved these changes
Only little comment

2020-05-26 07:19 UTC, sergio-teruel commented on website_megamenu/models/website_menu.py
> +    def _compute_field_is_mega_menu(self):
rename to _compute_is_mega_menu

2020-05-26 07:19 UTC, sergio-teruel commented on website_megamenu/models/website_menu.py
> +    def _set_field_is_mega_menu(self):
Rename to _inverse_is_mega_menu

2020-05-26 17:29 UTC, rafaelbn approved these changes
:+1: Thanks

@Tardo you have some minor comments from @sergio-teruel

2020-05-27 09:02 UTC, yajo requested changes

2020-05-27 09:02 UTC, yajo commented on website_megamenu/models/website_menu.py
> +    def _compute_field_is_mega_menu(self):
Although I'd generally agree, I think all he's done is copy upstream code from v13: https://github.com/odoo/odoo/blob/13.0/addons/website/models/website_menu.py#L20

So I think we better leave it as this, so there's less diff with upstream when this backport module is dropped in v13.

2020-05-27 09:02 UTC, yajo commented on website_megamenu/models/website_menu.py
> +    def _set_field_is_mega_menu(self):
Same as above, better as it is.

2020-05-27 09:02 UTC, yajo commented on website_megamenu/readme/CREDITS.rst
> +This module is a backport from Odoo SA and as such, it is not included in the
Please add a `ROADMAP.rst` indicating that this module should disappear for v13 and be merged into `website`.

2020-05-27 09:02 UTC, Yajo commented on website_megamenu/static/src/js/content.js
> +// License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
This is LGPL. The same in all files.

Also, please, in each file add a little comment in the top pointing to the upstream v13 file where code was imported from. This way, we know better how to compare it with upstream.

Thanks!

2020-05-27 10:14 UTC, sergio-teruel commented on website_megamenu/models/website_menu.py
> +    def _compute_field_is_mega_menu(self):
Ok

2020-05-27 11:55 UTC, Tardo commented
Changes done, renamed "views" folder to "templates".

2020-05-27 12:14 UTC, yajo approved these changes

2020-05-27 12:16 UTC, Yajo commented
/ocabot merge

2020-05-27 12:19 UTC, Yajo commented
/ocabot merge nobump

2020-05-27 13:05 UTC, merged