[MIG][10.0]website_google_tag_manager
OCA/website pull request #792
Opened 2020-11-05 16:18 UTC by SimoneVagile

2020-11-10 11:02 UTC, tafaRU requested changes
In addition to my previous comments:

- keep only one commit for the backporting migration (https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests as ref.)
- include in the commit message a reference to backporting from 11.0 to 10.0 i.e `[BKP] Backporting website_google_tag_manager from 11.0 to 10.0`

2020-11-10 11:02 UTC, tafaRU commented on website_google_tag_manager/__manifest__.py
> +    "author": "Agile Business Group, Odoo Community Association (OCA)",
Please re-add author removed by mistake. Also I don't think simply backporting deserves the module autorship!
So please restore the previous author string.

2020-11-10 11:02 UTC, tafaRU commented on website_google_tag_manager/models/website.py
> +# Copyright 2020 Simone Vanin - Agile Business Group
Why did you remove previous copyright?

2020-11-10 11:02 UTC, tafaRU commented on website_google_tag_manager/models/website_config_settings.py
> +# Copyright 2020 Simone Vanin - Agile Business Group
Same comment as above.

2020-11-10 11:02 UTC, tafaRU commented on website_google_tag_manager/views/website_config_settings_view.xml
> +                                <field name="google_tag_manager_key" placeholder="GTM-XXXXX"/>
What's the reason for removing `attrs` related part?

2020-11-10 11:02 UTC, tafaRU commented on website_google_tag_manager/readme/CONFIGURE.rst
> -To configure this module, you need to:
Don't remove this fragment file otherwise `oca-gen-addon-readme` used by OCA Bot will generate a wrong content fot the README file (see https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst for further info).

2020-11-10 11:02 UTC, tafaRU commented on website_google_tag_manager/readme/CONTRIBUTORS.rst
> -* `Sebastien Alix <sebastien.alix@osiell.com>`_
Same comment as above.

2020-11-10 11:02 UTC, tafaRU commented on website_google_tag_manager/readme/DESCRIPTION.rst
> -This module allows to configure your Odoo website to support the
Same comment as above.

2020-11-11 11:23 UTC, SimoneVagile commented on website_google_tag_manager/models/website.py
> +# Copyright 2020 Simone Vanin - Agile Business Group
Restored

2020-11-11 11:23 UTC, SimoneVagile commented on website_google_tag_manager/models/website_config_settings.py
> +# Copyright 2020 Simone Vanin - Agile Business Group
Restored

2020-11-11 11:23 UTC, SimoneVagile commented on website_google_tag_manager/__manifest__.py
> +    "author": "Agile Business Group, Odoo Community Association (OCA)",
Restored

2020-11-11 11:43 UTC, SimoneVagile commented on website_google_tag_manager/readme/CONFIGURE.rst
> -To configure this module, you need to:
I newly added this file and regenerated README by using `oca-gen-addon-readme`.

2020-11-11 11:43 UTC, SimoneVagile commented on website_google_tag_manager/readme/CONTRIBUTORS.rst
> -* `Sebastien Alix <sebastien.alix@osiell.com>`_
I newly added this file and regenerated README by using `oca-gen-addon-readme`.

2020-11-11 11:43 UTC, SimoneVagile commented on website_google_tag_manager/readme/DESCRIPTION.rst
> -This module allows to configure your Odoo website to support the
I newly added this file and regenerated README by using `oca-gen-addon-readme`.

2020-11-11 13:01 UTC, SimoneVagile commented on website_google_tag_manager/views/website_config_settings_view.xml
> +                                <field name="google_tag_manager_key" placeholder="GTM-XXXXX"/>
`google_management_client_id` field is not present in module `website` 10.0.
In 9.0 indeed:
[https://github.com/SimoneVagile/website/blob/9.0/website_google_tag_manager/views/website_config_settings.xml#L11](https://github.com/SimoneVagile/website/blob/9.0/website_google_tag_manager/views/website_config_settings.xml#L11)
In 12.0 was also removed:
[https://github.com/OCA/website/blob/12.0/website_google_tag_manager/views/res_config_settings_view.xml#L23](https://github.com/OCA/website/blob/12.0/website_google_tag_manager/views/res_config_settings_view.xml#L23)
So, `required` attribute is no longer necessary.

2020-11-11 13:23 UTC, tafaRU commented on website_google_tag_manager/views/website_config_settings_view.xml
> +                                <field name="google_tag_manager_key" placeholder="GTM-XXXXX"/>
Ok, so only in `11.0` is still present! Could you take the opportunity to create a PR to also fix it in this version?

2020-11-11 13:24 UTC, tafaRU commented
@SimoneVagile thanks for having addresses all my comments. But I noticed you don't preserve the commit history, could you please check it?

2020-11-11 15:38 UTC, SimoneVagile commented on website_google_tag_manager/views/website_config_settings_view.xml
> +                                <field name="google_tag_manager_key" placeholder="GTM-XXXXX"/>
[https://github.com/OCA/website/pull/800](https://github.com/OCA/website/pull/800)

2020-11-12 10:06 UTC, SimoneVagile commented
> @SimoneVagile thanks for having addresses all my comments. But I noticed you don't preserve the commit history, could you please check it?

Ok, I misunderstood your previous comment for sure: [https://github.com/OCA/website/pull/792#pullrequestreview-527072545](https://github.com/OCA/website/pull/792#pullrequestreview-527072545)
Hope this time is the right way.

2020-11-12 10:13 UTC, tafaRU commented
Ok @SimoneVagile now the commit history seems to be ok.
Last thing: please squash together the `[UPD] README.rst` commits (see https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-commits-in-pull-requests as reference).

2020-11-12 10:32 UTC, SimoneVagile commented
> Ok @SimoneVagile now the commit history seems to be ok.
> Last thing: please squash together the `[UPD] README.rst` commits (see https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-commits-in-pull-requests as reference).

Ok, done.

2020-11-12 10:43 UTC, tafaRU commented
The only `[UPD] README.rst` commit left makes little sense alone, I think it's better to squash with https://github.com/OCA/website/pull/792/commits/a2c6c38d4c22acc8417ace4a5e527e377abd13eb
I also noted the content of the last three commits of https://github.com/OCA/website/commits/11.0/website_google_tag_manager seems different compared to that one of https://github.com/OCA/website/pull/792/commits/7bdabaf812623aa02f6c8fbff04ebf28c763e047 Could you please check it?

2020-11-16 09:20 UTC, tafaRU approved these changes

2021-03-30 10:41 UTC, claudiagn approved these changes
functional review ok!

2022-12-18 12:33 UTC, closed without merging