14.0 mig website portal contact
OCA/website pull request #822
Opened 2021-02-08 13:18 UTC by chandni299

Migration of module "website_portal_contact" to v14

2021-02-08 13:25 UTC, pedrobaeza commented
I think this module needs at least a renaming, as no more dependency on website is needed for handling the portal. Thus, it can be moved to OCA/partner-contact.

2021-02-08 14:50 UTC, chandni299 commented
> I think this module needs at least a renaming, as no more dependency on website is needed for handling the portal. Thus, it can be moved to OCA/partner-con

Thanks ! Then what should be the new name or should I wait for a reply from Tecnativa's suggestion?

2021-02-08 15:31 UTC, pedrobaeza commented
Well, I'm from Tecnativa :wink: 

I good new name can be `portal_contact_mgmt`.

2021-03-30 10:37 UTC, claudiagn reviewed
I also think this should be moved to contract! 👍

2021-05-25 11:40 UTC, KilianNV approved these changes
LGTM

2021-05-25 14:11 UTC, MeetKD requested changes

2021-05-25 14:11 UTC, MeetKD commented on website_portal_contact/__manifest__.py
> +    "website": "https://tecnativa.com/",
Website should be as per oca guideline.

2021-05-25 14:11 UTC, MeetKD commented on website_portal_contact/controllers/main.py
> +        domain += [("id", "!=", request.env.user.partner_id.id)]
```suggestion
        domain += [("id", "!=", partner.id)]
```

2021-05-25 14:11 UTC, MeetKD commented on website_portal_contact/controllers/main.py
> +        Partner = request.env["res.partner"]
Do we need this variable?

2021-05-25 14:11 UTC, MeetKD commented on website_portal_contact/views/assests.xml
> +    <template id="assets_frontend" inherit_id="website.assets_frontend" name="Wishlist assets frontend">
```suggestion
    <template id="assets_frontend" inherit_id="website.assets_frontend" name="contact assets frontend">
```

2021-05-25 14:11 UTC, MeetKD commented on website_portal_contact/views/contact_portal_template.xml
> +
Can you please remove extra spaces?

2021-05-25 14:11 UTC, MeetKD commented on website_portal_contact/views/contact_portal_template.xml
> +                            <!-- <t t-call="website_portal_contact.form_field"/> -->
Please remove commented code.

2021-06-24 12:54 UTC, chandni299 commented
Hello @MeetKD , You will find the correct PR to review the code here for v14.
where now Migration of module "website_portal_contact" to v14 is moved to OCA/partner-contact with new module name "portal_contact_mgmt"
 [OCA/partner-contact/PR-1057](https://github.com/OCA/partner-contact/pull/1057)

2023-01-22 12:33 UTC, closed without merging