14.0 mig website crm privacy policy
OCA/website pull request #847
Opened 2021-10-04 11:46 UTC by pedroguirao

2021-10-13 10:47 UTC, victoralmau requested changes
It is important to put this block in the correct place.
Now:
![antes](https://user-images.githubusercontent.com/4117568/137118970-3ec8f8ee-25ef-4f07-8645-800dc60d68e0.png)

With my suggestions:
![despues](https://user-images.githubusercontent.com/4117568/137118986-49db8d59-b8ce-4e78-ad1e-603481d5510d.png)

2021-10-13 10:47 UTC, victoralmau commented on website_crm_privacy_policy/templates/contactus.xml
> +            expr="//form//div/div/span[@id='s_website_form_result']/../.."
```suggestion
            expr="//form//div/div/span[@id='s_website_form_result']/.."
```

2021-10-13 10:47 UTC, victoralmau commented on website_crm_privacy_policy/templates/contactus.xml
> +                <div class="offset-lg-3 offset-md-4 col-md-8 col-lg-7">
```suggestion
                <div class="col-sm" style="margin-left: 200px;">
```

2021-10-14 07:43 UTC, pedroguirao commented on website_crm_privacy_policy/templates/contactus.xml
> +                <div class="offset-lg-3 offset-md-4 col-md-8 col-lg-7">
Thank you Victor! its makes sense

2021-10-14 08:59 UTC, victoralmau commented
Please, can you unify your commits into one (Migration to 14.0)?

2021-10-14 10:16 UTC, pedroguirao commented
Hi Victor, first timer here, have to close this push and do a new one? or there is another way? Thank you

2021-10-14 11:53 UTC, victoralmau commented
In this same PR you must fix up those commits of yours in just one.

2021-10-14 15:11 UTC, pedrobaeza commented
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2021-10-19 09:51 UTC, pedroguirao commented
Thank you Victoralmau and Pedrobaeza, hope it's OK

2022-01-23 18:49 UTC, JordiBForgeFlow commented
@pedroguirao can you close this PR?

2022-01-27 11:25 UTC, pedroguirao commented
Sorry @JordiBForgeFlow, Im going to close it now.

2022-01-27 11:25 UTC, closed without merging