[13.0][MIG] website_snippet_big_button: Migration to 13.0
OCA/website pull request #868
Opened 2022-01-05 16:59 UTC by willytal

Standard procedure

TT27594 @Tecnativa

2022-01-05 17:02 UTC, willytal commented
cc @Tardo @pedrobaeza

2022-01-05 17:24 UTC, pedrobaeza approved these changes
Functional test in runboat

2022-01-05 17:25 UTC, pedrobaeza commented
/ocabot migration website_snippet_big_button

2022-01-07 07:13 UTC, victoralmau requested changes
Good job, only some little changes and squash administrative commits too.

2022-01-07 07:13 UTC, victoralmau commented on website_snippet_big_button/i18n/es.po
> +#~ msgstr "Solicitar presupuesto"
```suggestion
```

2022-01-07 07:13 UTC, victoralmau commented on website_snippet_big_button/i18n/fr.po
> +#~ msgstr "Je veux autre chose"
```suggestion
```

2022-01-07 07:13 UTC, victoralmau commented on website_snippet_big_button/i18n/pt_BR.po
> +#~ msgstr "Solicitar orçamento"
```suggestion
```

2022-01-07 07:13 UTC, victoralmau commented on website_snippet_big_button/i18n/sl.po
> +#~ msgstr "Zahtevaj proračun"
```suggestion
```

2022-01-07 07:13 UTC, victoralmau commented on website_snippet_big_button/__manifest__.py
> +# Copyright 2022 Tecnativa - Guillermo Gallego <guillermo.gallego@tecnativa.com>
```suggestion
# Copyright 2015-2016 Tecnativa - Jairo Llopis
# Copyright 2019 Tecnativa - Cristina Martin R.
# Copyright 2022 Tecnativa - Guillermo Gallego
```

2022-01-07 07:13 UTC, victoralmau commented on website_snippet_big_button/templates/assets.xml
> +<!-- # Copyright 2015-2016 Tecnativa - Jairo Llopis <jairo.llopis@tecnativa.com>
```suggestion
<!-- # Copyright 2015-2016 Tecnativa - Jairo Llopis
```

2022-01-07 07:13 UTC, victoralmau commented on website_snippet_big_button/templates/snippets.xml
> +<!-- Copyright 2015-2016 Jairo Llopis <jairo.llopis@tecnativa.com>
```suggestion
<!-- Copyright 2015-2016 Jairo Llopis
```

2022-01-07 15:56 UTC, Tardo requested changes
It is not necessary to define your own classes for the styles being applied. So you can delete the .scss file and use bootstrap.

2022-01-07 15:56 UTC, Tardo commented on website_snippet_big_button/static/src/scss/website_snippet_big_button.scss
> +}
Don't need this css rules
```suggestion
```

2022-01-07 15:56 UTC, Tardo commented on website_snippet_big_button/templates/snippets.xml
> +                            class="btn btn-success btn-lg font-weight-bold"
```suggestion
                            class="btn btn-success btn-lg font-weight-bold d-flex flex-column justify-content-around"
```

2022-01-07 15:56 UTC, Tardo commented on website_snippet_big_button/templates/snippets.xml
> +                    <div class="text-center col-sm-6 offset-lg-2 col-lg-4 pb8">
```suggestion
                    <div class="text-center justify-content-center col-sm-6 col-lg-4 pb8">
```

2022-01-07 15:56 UTC, Tardo commented on website_snippet_big_button/templates/snippets.xml
> +                        <a href="/" class="btn btn-danger btn-lg font-weight-bold">
```suggestion
                        <a href="/" class="btn btn-danger btn-lg font-weight-bold d-flex flex-column justify-content-around">
```

2022-01-20 14:11 UTC, Tardo approved these changes

2022-01-20 14:12 UTC, pedrobaeza commented
/ocabot merge nobump

2022-01-20 14:50 UTC, merged