[15.0][MIG] website_cookiebot: Migration to version 15.0
OCA/website pull request #935
Opened 2023-01-02 12:29 UTC by stefan-tecnativa

cc @Tecnativa TT39017

@chienandalu @pedrobaeza please review!

2023-01-03 11:38 UTC, chienandalu requested changes

2023-01-03 11:38 UTC, chienandalu commented on website_cookiebot/templates/website.xml
> +    </template>
Check this other module implementation that will give you a clue on how to make it better (inherit from that other template): https://github.com/OCA/website/blob/14.0/website_legal_page/views/website_legal_main_page.xml#L4-L18

2023-01-04 11:32 UTC, chienandalu approved these changes
:+1:

2023-01-06 15:33 UTC, pedrobaeza commented
/ocabot migration website_cookiebot

2023-01-06 15:37 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-01-06 15:42 UTC, merged