12.0 mig website prevent cls
OCA/website pull request #993
Opened 2023-07-20 14:40 UTC by Legostaiman

2023-07-21 08:30 UTC, em230418 requested changes
Последние 3 коммита склей в один, пожалуйста.

2023-07-21 08:38 UTC, em230418 commented on website_prevent_cls/tools/image.py
> +Image._initialized = 2
Вместо всего этого предлагаю просто импортировать из odoo.tools.image все, что нужно для выполнения функции base64_to_image, которую переписал ниже

2023-07-24 18:56 UTC, Legostaiman commented on website_prevent_cls/tools/image.py
> +Image._initialized = 2
@em230418 Я перенёс это потому что в версии 12 нет того, что используют в версии 13. Возможно, я не внимательно посмотрел, проверю ещё раз.

2023-07-25 08:24 UTC, em230418 commented on website_prevent_cls/tools/image.py
> +Image._initialized = 2
> Возможно, речь о том, чтобы перенести тело функции в метод _get_image_size()

Нет. 

> Я перенёс это потому что в версии 12 нет того, что используют в версии 13. 

То, что перенес метод base64_to_image - это правильно. Речь же сейчас про строки 1-14. Они присутствуют в модуле odoo.tools.image и я предлагаю вместо этих строк просто импортировать из odoo.tools.image переменные, которые нужны для выполнения метода base64_to_image, которая идет ниже в твоем файле tools/image.py.

Одна из причин, почему я так предлагаю сделать - это строки 13-14. Они избыточны, ибо при импорте чего либо из odoo.image.tools уже вызываются выражения из этих строк.

2023-07-26 09:07 UTC, Legostaiman commented on website_prevent_cls/tools/image.py
> +Image._initialized = 2
@em230418 Евгений, спасибо, понял Вас, сегодня вечером внесу эти изменения.

2023-07-27 07:30 UTC, em230418 approved these changes
LGTM
Добро!

2023-12-31 12:31 UTC, closed without merging