[ADD]website_rewrite_absolute_url: Module to add absolute url redirects
OCA/website pull request #994
Opened 2023-07-21 08:58 UTC by odooNextev

By default Odoo doesn't allow to add absolute url redirects. I added "Is absolute url" field, if it's checked, then it will be possible to add an absolute url redirects. 
In check_url_to method I replicated default behaviours, but using routing_map.bind(rewrite.url_to) if it's an absolute url.

2024-01-08 15:41 UTC, odooNextev commented
@pedrobaeza What is your opinion about this pr?

2024-01-08 18:54 UTC, pedrobaeza commented
I can't say about the functionality, sorry. Reopening for now.

2024-01-09 10:33 UTC, yajo requested changes
This module is unnecessary AFAICS.

Just make sure you add `http://` or `https://` at the beginning of the redirected URL and base odoo will work out of the box.

Something like this:
![imagen](https://github.com/OCA/website/assets/973709/3cde434c-e6fd-4cb3-9af2-8824d0e0e7df)

It will perform the expected absolute redirection, without needing this module.

2024-01-09 10:40 UTC, odooNextev commented
Thanks @yajo, It works properly without this module.

2024-01-09 10:40 UTC, closed without merging